### ISSUE TITLE
replace python by python3

### ISSUE THREAD

**Issue by VictorEijkhout** [cburstedde/p4est#122]
There are files in the distribution that contain

```
#!/usr/bin/env python
```

The rpm package manager considers that an error and insists on python2 or 3 explicitly. (In other words: my attempt to turn p4est into an rpm failed.) Might be an an idea to consider?

**Comment by cburstedde** [comment]
Thanks, can you help me out and tell me which files?

**Comment by cburstedde** [comment]
Huh that's a file under doc. Not relevant at all to the sources. Can you just remove it in your packaging script?

**Comment by cburstedde** [comment]
I'll change it to python2 in upcoming relases.

**Comment by VictorEijkhout** [comment]
On , 2021Sep30, at 04:50, Carsten Burstedde ***@***.******@***.***>> wrote:

Can you just remove it in your packaging script?

I guess, but I don’t like special cases.

For now I’ve found how to disable that test.

Victor.

**Comment by cburstedde** [comment]
Cool. Thanks for calling it. Fixed already in the development sources.
