### ISSUE TITLE
CMake build system does not create a correct p4est_config.h

### ISSUE THREAD

**Issue by Rombur** [cburstedde/p4est#125]
There are a couple of issues with the `p4est_config.h` file created by the CMake build system:
1.  the version is wrong, it is set at `2.0.94-00da` instead of 2.8 https://github.com/cburstedde/p4est/blob/v2.8/cmake/p4est_config.h.in#L137-L159
2. I am not sure if this is a bug or not but `P4EST_ENABLE_VTK_BINARY` and `P4EST_ENABLE_VTK_COMPRESSION` are always set. Shouldn't you use `cmakedefine` instead of `define`  https://github.com/cburstedde/p4est/blob/v2.8/cmake/p4est_config.h.in#L46-L50

**Comment by cburstedde** [comment]
> There are a couple of issues with the `p4est_config.h` file created by the CMake build system:
> 1.  the version is wrong, it is set at `2.0.94-00da` instead of 2.8 https://github.com/cburstedde/p4est/blob/v2.8/cmake/p4est_config.h.in#L137-L159
> 2. I am not sure if this is a bug or not but `P4EST_ENABLE_VTK_BINARY` and `P4EST_ENABLE_VTK_COMPRESSION` are always set. Shouldn't you use `cmakedefine` instead of `define`  https://github.com/cburstedde/p4est/blob/v2.8/cmake/p4est_config.h.in#L46-L50

Thanks!  Would you be able to repair this yourself?  We don't have regular core
support for CMake.  You may use the feature-cmake branch for such development.

**Comment by Rombur** [comment]
I should be able to fix it. I'll let you know if I need help.

**Comment by cburstedde** [comment]
Thanks, I appreciate your work on p4est. If you'd feel like doing the analog in libsc, we'd be really happy about it.

**Comment by cburstedde** [comment]
It seems there's not really something to carry over into sc.
