### ISSUE TITLE
Bug in `p6est_lnodes` comment?

### ISSUE THREAD

**Issue by jkozdon** [cburstedde/p4est#128]
Am I correct in that this comment should also say that the edges are also differently numbered.

https://github.com/cburstedde/p4est/blob/45ea68a91d11ee15172bc8e6336ed62c91f09cf4/src/p6est_lnodes.h#L40-L41

**Comment by cburstedde** [comment]
Ok, while we're at it, let's discuss whatever remains to do in #129.
