### ISSUE TITLE
Make sure compilers are called with C99 flags

### ISSUE THREAD

**Issue by bangerth** [cburstedde/p4est#133]
One of the deal.II users was told by a supercomputing center to use their Intel compiler. That led to a number of errors, the first one of which was 
```
 /home/saspark2/build2//tmp/unpack/p4est-2.3.2/src/p8est_connectivity.c(930):
 error: expected an expression
       for (int i=0; i<num_vertices*3; ++i)
            ^ 
```
The issue is that that compiler is apparently still stuck on C89. Declaring variables in a `for` loop is a C99 feature. That p4est wants to compile in C99 mode is something that the compiler should be told on the command line, via the configuration script.

**Comment by cburstedde** [comment]
Oh I missed that construction on a merge in the past. We'll definitely move the declaration out of the loop.

**Comment by cburstedde** [comment]
This is done on prev3-develop. Does everything build fine without flags now?

**Comment by tjhei** [comment]
We are not sure because these are just user reports (from ASPECT) and it is difficult for us to ask them to reproduce this with a development version.

**Comment by cburstedde** [comment]
Ok, if anything like this pops up again, issues can be reopened or newly posted.

**Comment by tjhei** [comment]
Thank you. Would it be possible for you to do a point release soon?

**Comment by cburstedde** [comment]
It should be fine to come up with a new version number soon-ish. One more thing I'd like to do, but not much.
