### ISSUE TITLE
Variable size of data attached to cells before rebalancing

### ISSUE THREAD

**Issue by bangerth** [cburstedde/p4est#15]
If my understanding is correct, then the data that can be attached to a cell upon rebalancing (and that will then be available for unpacking on the cell's new process) must have the same size for all cells. This is appropriate for meshes where one uses the same polynomial degree for the finite element spaces on all cells.

But it gets us into trouble in two situations:
- hp finite elements, where each cell may have a different polynomial degree, and the data to be attached is of different length as a consequence.
- We are implementing particle methods where on every cell there are zero or more particles that have to be transported along with the cell data upon rebalancing. There are cells where we have a lot of particles (dozens or maybe over a hundred), but there are also many cells that have zero particles (e.g., if we just want to track where material that originated in a part of the domain ends up). Consequently, the amount of data that needs to be attached to each cell is vastly different, from zero bytes to potentially several kB. 

In the current scheme, both of these scenarios require transferring a lot of zeros that just pad each cell's buffer up to the size of the buffer on the cell with the largest amount of attached data. This is not efficient.

**Comment by bangerth** [comment]
@gassmoeller -- you may be interested in this topic and possible solutions.

**Comment by cburstedde** [comment]
> If my understanding is correct, then the data that can be attached to a cell upon rebalancing (and that will then be available for unpacking on the cell's new process) must have the same size for all cells. This is appropriate for meshes where one uses the same polynomial degree for the finite element spaces on all cells.

This is true -- p4est_partition takes care of communicating quadrant
user data, which is fixed-size.

> But it gets us into trouble in two situations:
> * hp finite elements, where each cell may have a different polynomial degree, and the data to be attached is of different length as a consequence.
> * We are implementing particle methods where on every cell there are zero or more particles that have to be transported along with the cell data upon rebalancing. There are cells where we have a lot of particles (dozens or maybe over a hundred), but there are also many cells that have zero particles (e.g., if we just want to track where material that originated in a part of the domain ends up). Consequently, the amount of data that needs to be attached to each cell is vastly different, from zero bytes to potentially several kB. 

And many more scenarios to imagine.

> In the current scheme, both of these scenarios require transferring a lot of zeros that just pad each cell's buffer up to the size of the buffer on the cell with the largest amount of attached data. This is not efficient.

I'm working on a variable-size data communication function, for data
that lives in user and not p4est space.  I would be curious to see who
would be interested in using it -- please leave a comment to let me
know, and requests for features.

**Comment by bangerth** [comment]
Clearly, the deal.II and ASPECT communities are interested :-)

**Comment by cburstedde** [comment]
Stay tuned. Expecting to release it in fall.

**Comment by cburstedde** [comment]
I've update the master branch with new code in p4est_communication.
Check out the p4est_transfer functions: They should do what you need.

**Comment by cburstedde** [comment]
If you have comments on the functionality, please reopen.

**Comment by gassmoeller** [comment]
Sorry for not coming back earlier to this, and thanks for providing this functionality! I did not yet have the time to use it, but I definitely will in the next months. I will keep you up-to-date.

**Comment by marcfehling** [comment]
@bangerth  and I are currently thinking about how to apply the variable-size data communication of p4est to deal.II. Up to this point, deal.II is calling the p4est_partition_ext function, which itself calls the p4est_partition_given function for data exchange upon the repartitioned tree in p4est v2.0. As far as I can tell, the latter uses the MPI interface itself for communication, but none of the p4est_transfer functions.
https://github.com/cburstedde/p4est/blob/a9910fd70d2645d90b7429b4fb596c21b8dbe75e/src/p4est.c#L2430-L2432
https://github.com/cburstedde/p4est/blob/a9910fd70d2645d90b7429b4fb596c21b8dbe75e/src/p4est_algorithms.c#L2707-L2709

---

So I wanted to ask if it would be generally possible to take advantage of these transfer functions in p4est_partition_given to unify transfer processes and avoid code duplicates in p4est? Or would it be more convenient to separate partitioning and data transfer like @tisaac already proposed in his fork https://github.com/tisaac/p4est/commit/4cae74f5299e83885c29d45d631f02ad160ba0bf and @cburstedde mentioned in his most recent [paper](https://arxiv.org/abs/1803.08432).
https://github.com/cburstedde/p4est/blob/a9910fd70d2645d90b7429b4fb596c21b8dbe75e/src/p4est_communication.c#L922-L926
https://github.com/cburstedde/p4est/blob/a9910fd70d2645d90b7429b4fb596c21b8dbe75e/src/p4est_communication.c#L1172-L1177

---

@cburstedde or anybody else: Do you probably have some example code to share that demonstrates how to use the new transfer functions together with repartitioning a forest? That would be great!

**Comment by bangerth** [comment]
So you'd have to store an array with the quadrants and an array with corresponding data as inputs for the function, where the quadrants were stored locally BEFORE the partitioning? That should be pretty easy to generate - it's basically a map of (destination, data) pairs.

**Comment by cburstedde** [comment]
> So you'd have to store an array with the quadrants and an array with corresponding data as inputs for the function, where the quadrants were stored locally BEFORE the partitioning? That should be pretty easy to generate - it's basically a map of (destination, data) pairs. 

The data before and after are two distinct flat arrays, and there is one
integer array for each with the per-element data sizes.

I am considering to use cumulative size offsets instead of the sizes themselves
-- so the application would not need to track offsets or pointers separately.
However, this would require more work on the inside.  Can you try the current
interface first and let me know if you'd rather switch the API to cumulative?

**Comment by bangerth** [comment]
I don't think we have a preference between sizes or offsets (cumulative). One is easy to convert into the other -- it makes no difference in ease of use.

**Comment by marcfehling** [comment]
Wait -- I guess I understood that wrong in the first place!

We do not have to attach our data to the <code>user_data</code> of each quadrant anymore, but rather store the global first quadrant before and after partitioning? They keep track of the element count and the markers and thus provide the information necessary to transfer the data externally. Thus, we do not have to keep track of the <code>user_data</code>, which will be sent in <code>p4est_partition_given</code>! I assumed that this is still the case, what really confused me. [And now I see that exactly this is mentioned in the documentation of <code>transfer_fixed</code> -- shame on me!]

Your implementation appears really convenient! Now I need to rethink my approach...
