### ISSUE TITLE
Explicitly link against external libsc if `-with-sc=...` is specified

### ISSUE THREAD

**Issue by tamiko** [cburstedde/p4est#16]
I have written two independent ebuilds for Gentoo (maintained in the Gentoo science overlay [1,2]):

I use the `--with-sc=` configure switch in p4est to build against external libsc, but the system libsc is not registered as a shared object dependency. Thus, in order to avoid underlinkage I have to manually specify
```
LDFLAGS="${LDFLAGS} -lsc"
```

Could this be added to the build system?

[1] https://github.com/gentoo-science/sci/tree/master/sci-libs/libsc
[2] https://github.com/gentoo-science/sci/tree/master/sci-libs/p4est

**Comment by cburstedde** [comment]
> I have written two independent ebuilds for Gentoo (maintained in the Gentoo science overlay [1,2]):
> 
> I use the `--with-sc=` configure switch in p4est to build against external libsc, but my system libsc is not registered as a shared object dependency. Thus, in order to avoid underlinkage I have to manually specify
> ```
> LDFLAGS="${LDFLAGS} -lsc"
> ```
> 
> Could this be added to the build system?

Thanks for maintaining these packages.

I do the same on my 12.04 lts ubuntu installation it works out.
See sc/config/sc_package.m4:

  $1_$3_LDADD="$$1_$3_DIR/lib/lib$4.la"

so p4est grabs the sc .la file.  In my make installed libsc I find

libsc-1.1.265-1247.so
libsc-1.1.266-26c3.so
libsc.a
libsc.la
libsc.so ->libsc-1.1.266-26c3.so

and all the p4est examples build.

Also, take a look at the installed Makefile.p4est.mk.  If users include
this in their custom (non-autotools) Makefile, it should grab the sc
dependencies automatically.

What would be the right fix for Gentoo?  Do we need one?

> [1] https://github.com/gentoo-science/sci/tree/master/sci-libs/libsc
> [2] https://github.com/gentoo-science/sci/tree/master/sci-libs/p4est

**Comment by tamiko** [comment]
Ah, nevermind.

I completely forgot, what I did years ago.

The problem is that I do not install the corresponding *.la files on Gentoo due to distribution policies.
So, there is nothing to be done upstream (the ebuild makes sure p4est is linked properly).
