### ISSUE TITLE
refinement tag in quadrant structure

### ISSUE THREAD

**Issue by mirzadeh** [cburstedde/p4est#17]
This is not so much of an issue but perhaps a question or request for enhancement. 

Currently the API for refinement/coarsening requires decision to be made on-the-fly for each quadrant. This is needed for recursive refinement. For non-recursive refinement, this approach works fine for simple refinement/coarsening schemes, but complicates more nontrivial uses, e.g. consider the following situation:

``` c
solve_u1_and_set_refinement_flag();
// lots of code perhaps across several files
solve_u2_and_set_coarsening_flag();
// lots of code perhaps across several files
invoke_refinement_and_coarsening();
```

Here `u1` and `u2` could be two entirely separate physical variables, each with its own solution phase and refinement requirements. Since the user does not necessarily know the requirements of individual solvers, and they could be entirely independent, they are best left to individual solvers. Naturally one then would like to let each solver first go through setting/clearing flags (perhaps even overwriting each other) and finally call the refinement/coarsening functions. 

At the moment this approach _is possible_ but is somewhat convoluted. One needs to have a separate list and iterate through it via callback functions. The list then has to be passed via `p4est->user_pointer`, which would need extra bookkeeping  if the pointer is already occupied by another data.  Having a dedicated tag inside the quadrant easily solves this problem. Arguably this won't work with recursive refinement but that could be handled via existing approaches if needed. Also, in practice most of the refinement/coarsening would be non-recursive anyway.

Currently I have been (mis)using the `quad->p.user_int` since I did not have any data attached to the quadrants. Obviously this won't work if one does have extra data attached. There are `pad8` and `pad16` elements as well which seem to be only used for padding. Perhaps one of them could be reused as `refinement_tag` but I am not sure if its good practice to rely on them? Perhaps one of them could be renamed to indicate appropriate use but that might be a breaking change.

What's the best approach?

**Comment by cburstedde** [comment]
I'm reluctant to touch any of the pad fields at all. Some are used internally in refine/coarsen, which makes external use rather unpredictable.

(1) You can rely on the fact that the refine/coarsen callbacks are called ordered and once for every local quadrant, at least non-recursively, so you can do some pointer++ to step through an array of flags. If this feature is broken, please let us know.

(2) To make passing user data more transparent, have a look at the feature-pdest branch. I'm not at all sure that a dimension-independent API is needed, but it is somewhat better designed in a couple places. Comments welcome.

**Comment by cburstedde** [comment]
Bump - what do you think (esp. re (2))?

**Comment by mirzadeh** [comment]
Sorry I forgot to respond earlier. I think I had used the first approach before and it did work although I was not sure if it was guaranteed. Good to know that is the case. 

I somehow missed the second suggestion. I'll check out the branch and come back to you. Although passing data was never really a challenge for my problems :). 

Please feel free to close this one.
