### ISSUE TITLE
libp4est / libsc should have a proper SOVERSION

### ISSUE THREAD

**Issue by StefanBruens** [cburstedde/p4est#174]
**Description**

Both libraries should have a SOVERSION which gets bumped every time the ABI is changed in an incompatible way.

**Proposed solution**

https://cmake.org/cmake/help/latest/prop_tgt/SOVERSION.html

**Comment by cburstedde** [comment]
Thanks; after I hook the latest libsc into p4est, this can be addressed.

**Comment by StefanBruens** [comment]
Is it actually intended to have a SOVERSION (ABI) bump on every patch version change?

This is not wrong per se, but will force everyone to rebuild/relink all dependent packages on each version change.

**Comment by cburstedde** [comment]
I have just introduced -version-info to libtool at all. The production releases of p4est and libsc are at 2:0:0.

I'll try to update these numbers as infrequently as possible. This one change from 0:0:0 appears long overdue.

Do you have further comments on versioning and packaging?

**Comment by cburstedde** [comment]
And, I have not changed anything in CMAke. I'll be happy to look at any contributions that align the versioning produced by CMake to the authoritative produced by autoconf/automake/libtool.

**Comment by StefanBruens** [comment]
The SOVERSION property should be the same as the `current - age`.`revision` from the libtool versioning (i.e. `2.0` for `2:0:0`).

**Comment by cburstedde** [comment]
Would you like to add this properly to the libsc and p4est CMake files?
