### ISSUE TITLE
Assertion failure in p8est_balance_seeds

### ISSUE THREAD

**Issue by cburstedde** [cburstedde/p4est#186]
**Description**

The latest master branch, which refers to the compatibility chain with very conservative code, crashes on calling:

    example/balance_seeds/p8est_balance_seeds

with an assertion `p4est_quadrant_is_extended (r)`.

This happens only in debug mode. Non-debug runs valgrind clean. Configure line is:

    /path/to/configure --enable-debug --enable-mpi --disable-shared \
        --without-blas CFLAGS="-g -Wall -Wextra -Wno-unused-parameter -pedantic

and various other variants, in particular without MPI.

@tisaac, any ideas?

**Comment by pkestene** [comment]
I think this is just due to the fact that, in the 3d case, the coordiantes of the center quadrant must be adapted, because this example was made when P8EST_MAXLEVEL was19, now it is 30.
