### ISSUE TITLE
Valgrind errors

### ISSUE THREAD

**Issue by prj-** [cburstedde/p4est#191]
Could you please merge changes from https://github.com/cburstedde/p4est/compare/develop...tisaac:p4est:tisaac/petsc to make the code Valgrind-clean?

**Comment by cburstedde** [comment]
Thanks for the heads-up. We have made some of these changes on our side but are looking into it.

Hi @tim-griesbach, could you please check whether "master" can be merged cleanly into @tisaac's petsc branch?

**Comment by tim-griesbach** [comment]
I merged the current master branch in @tisaac's petsc branch and resolved the merge conflicts. The resulting branch is https://github.com/tim-griesbach/p4est/tree/petsc. Now, we could merge this branch into master with https://github.com/cburstedde/p4est/compare/master...tim-griesbach:p4est:petsc as diff.
