### ISSUE TITLE
Too restrictive configure tests for MPI environment since p4est v2.8.5

### ISSUE THREAD

**Issue by jmark** [cburstedde/p4est#197]
**Description**

Something changed in the build system from version 2.8 to 2.8.5 leading to failed configure-runs on several platforms.

See https://buildkite.com/julialang/yggdrasil/builds/2292 for detailed error logs.

**To Reproduce**
This PR https://github.com/JuliaPackaging/Yggdrasil/pull/6578/files has all the information.

@cburstedde @sloede @JoshuaLampert

**Comment by jmark** [comment]
Amongst others the commit https://github.com/cburstedde/libsc/commit/cfc2ca3cde30950d57287d3c63f0d062afc3632e in `libsc` causes troubles for configuring on some platforms.

**Comment by sloede** [comment]
From a cursory look, it seems to me like the new MPI tests that were added are implemented sich that they assume that the MPI constants are *compile-time* constants, whereas the MPI standard only stipulates that they are *constant*.

**Comment by cburstedde** [comment]
Thanks for pointing it out!
