### ISSUE TITLE
Dlopen on libp4est not working anymore.

### ISSUE THREAD

**Issue by jmark** [cburstedde/p4est#204]
**Description**

When `dlopen` the dynamic `libp4est.so` it raises errors about not finding symbols from `libsc.so`.
The reason for this is, that the linking information to `libsc.so` is not stored in `libp4est.so` anymore
as was in previous releases.

@cburstedde @sloede

**Comment by cburstedde** [comment]
See #208. Supposed this works, it will not be hard to have t8code inherit the logic.

**Comment by jmark** [comment]
Fixed.

**Comment by cburstedde** [comment]
This should all be fine on the develop branches of the codes. Comments?
