### ISSUE TITLE
cmake variable sc_external used before defined

### ISSUE THREAD

**Issue by pkestene** [cburstedde/p4est#213]
**Description**

In top-level CMakeLists.txt variable `sc_external` is used at line 33 (https://github.com/cburstedde/p4est/blob/master/CMakeLists.txt#L33), while it is defined inside `cmake/sc.cmake` that is not sourced yet.

**Proposed solution**

As sc_external behave like an option, just make it actually a cmake option and move its definition inside `cmake/options.cmake`

**Comment by cburstedde** [comment]
Thanks; this appears resolved! :)
