### ISSUE TITLE
Help with connectivity [not really an issue]

### ISSUE THREAD

**Issue by stichou** [cburstedde/p4est#216]
Hello,

  I am learning to use p4est from scratch and I am encountering a problem with connectivities and geometry.
I am trying to create a connectivity and geometry as: 
``` C
conn = p4est_connectivity_new_disk2d ();
geom = p4est_geometry_new_disk2d (conn, 2, 10);
```

But I get following warnings that lead to erros:
``` bash
warning: implicit declaration of function ‘p4est_connectivity_new_disk2d’; did you mean ‘p4est_connectivity_new_disk’? [-Wimplicit-function-declaration]
warning: implicit declaration of function ‘p4est_geometry_new_disk2d’; did you mean ‘p4est_geometry_destroy’? [-Wimplicit-function-declaration]
```

I do not understand these warnings/errors since:
- I can use other basic p4est connectivities and geometries in my program 
- I am able to run correctly following program that uses `*_new_disk2d`:
``` C
mpirun -np N p4est_simple disk 8
```
Should I include another module of p4est in my program ?

Thank you for your help,
Steven

P-S: 
- I built an mpi version as Pr. Burstedde showed in __2020 Hausdorff School on p4est/1: A Brief Tour of p4est__ and all examples are working correctly.
- I am including following modules in my program:
``` C
#include <p4est.h>
#include <p4est_bits.h>
#include <p4est_extended.h>
#include <p4est_vtk.h>
#include <p4est_connectivity.h>
```

**Comment by pkestene** [comment]
Hi @stichou,

several remarks:
- API  `p4est_connectivity_new_disk2d` is declared in header `p4est_connectivity.h`, so there shouldn't be any warning if you are using this API after including this header and using a fairly recent version of p4est
- you should also include `p4est_geometry.h`
- in your example `mpirun -np N p4est_simple disk 8`, you are probably actually using the `disk` connectivity, not `disk2d` which are two different connectivities.

Can you report which version of p4est you are using ?
Can you check that the p4est_simple.c source code actually contain the `disk2d` connectivity call (just to make sure you are using a fairly recent version of p4est) ?

Just a hypothesis : is that possible that you are on a machine that already has a version of p4est installed through a package manager (e.g. on ubuntu, apt install libp4est-dev); in that case, depending on a how you build your application, how the compilation flags are passed to the compiler, the p4est headers from the system might be used by the compiler, and, in that case, it might be an old version of p4est, where disk2d was not already in the master branch and lead to compilation errors.

**Comment by stichou** [comment]
HI @pkestene,

  Your first guess was right, indeed I checked and libp4est-dev is already installed in my system and I am surely using this instead of my build.

  However I am a beginner with linking libraries and I am afraid I am doing things wrong. Can you help we with that please ? I am following the steps in https://www.p4est.org/tutorial-build.html where it is explained how to link libraries with -I -L. However, in my build I don't have the standard `include` and `lib` folder. Which folders should I use as include and lib, please ? 

  Here is the content of my build folder:
``` bash
config  config.log  config.status  doc  example  libtool  Makefile  sc  src  test
```

Thank you for your help,
Steven

**Comment by pkestene** [comment]
Ok, I see, you built p4est; all you need now is to install p4est, i.e. copy the library and the headers in a known location. Then you will have a standard installation with a `lib` and `include` directories.

I advise you:
1. rerun the configure script using flag `--prefix=/somewhere/on/yourplatform`; this flag allows you to specify the installation path, i.e. where you want to install p4est on your platform. It can be somewhere in your home directory. One possibility is `$HOME/.local`; personnally, I use something like `$HOME/local/p4est-$P4EST_VERSION` 
2. rerun `make`
3.  run `make install`; it will populate the installation directory

To build your app using `p4est` you just need to use the `include` and `lib` rooted in the installation path, i.e. use flags `-I$P4EST_INSTALL_PATH/include` and `-L$P4EST_INSTALL_PATH/lib`.

One additional thing: if you build p4est as a shared library (libp4est.so), you also need to setup env variable `LD_LIBRARY_PATH`
```shell
export LD_LIBRARY_PATH=$P4EST_INSTALL_PATH/lib:$LD_LIBRARY_PATH
```
it will ensure that at runtime, your application will use the p4est library you've just installed, not the one from the package manager.
If you built p4est as a static library (libp4est.a), you don't need that.
