### ISSUE TITLE
is it possible to avoid flock()?

### ISSUE THREAD

**Issue by asartori86** [cburstedde/p4est#22]
Hi,

I am encountering some problems in saving the mesh because it seems it calls the `flock()` function but the file system on our cluster does not allow it. 

Could it be avoided? 

I would be glad to contribute with a patch if you can guide me a bit

Thanks

**Comment by cburstedde** [comment]
> I am encountering some problems in saving the mesh because it seems it calls the `flock()` function but the file system on our cluster does not allow it. 
> 
> Could it be avoided? 
> 
> I would be glad to contribute with a patch if you can guide me a bit

There is no explicit call to flock in the code except for
sc/src/sc_getopt. which is probably not what you are referring to.

Is it possible that the MPI I/O implementation you're using calls it?

**Comment by cburstedde** [comment]
Maybe you're version is way old. If the problem persists, please reopen.
