### ISSUE TITLE
libsc is not included in v2.0

### ISSUE THREAD

**Issue by masterleinad** [cburstedde/p4est#23]
The realease `v2.0` does neither contain `libsc` in the `sc` folder nor a `./configure` script.
Copying `v2.0` of `libsc` to the folder `sc` and running `./bootstrap` creates `./configure` and allows installation then.

**Comment by cburstedde** [comment]
> The realease `v2.0` does neither contain `libsc` in the `sc` folder nor a `./configure` script.
> Copying `v2.0` of `libsc` to the folder `sc` and running `./bootstrap` creates `./configure` and allows installation then.

The github mechanism of packing releases into tarballs does not work for
us.  We offer working .tar.gz files of p4est and libsc on the
p4est.github.io webpage; see for example:
http://p4est.github.io/release/p4est-2.0.tar.gz

Alternatively, clone the repository, ./bootstrap, configure and make dist.

**Comment by cburstedde** [comment]
On Mon, Mar 20, 2017 at 07:42:30PM +0100, Carsten Burstedde wrote:
> > The realease `v2.0` does neither contain `libsc` in the `sc` folder nor a `./configure` script.
> > Copying `v2.0` of `libsc` to the folder `sc` and running `./bootstrap` creates `./configure` and allows installation then.
> 
> The github mechanism of packing releases into tarballs does not work for
> us.  We offer working .tar.gz files of p4est and libsc on the
> p4est.github.io webpage; see for example:
> http://p4est.github.io/release/p4est-2.0.tar.gz
> 
> Alternatively, clone the repository, ./bootstrap, configure and make dist.

And get the git submodule under sc after cloning and before bootstrap.

**Comment by masterleinad** [comment]
That `p4est-2.0.tar.gz` works fine.
