### ISSUE TITLE
Build with Windows?

### ISSUE THREAD

**Issue by Haider-BA** [cburstedde/p4est#24]
How to build p4est in windows either with VS or MSYS etc.?

**Comment by cburstedde** [comment]
I don't know. If you figure it out, please feel free to put some documentation into the doc subdirectory.

**Comment by mike-matveev** [comment]
Hi all,

I have managed to build the package with MSYS2/MinGW64 and then link it to MS VS. The instruction is in the new pull request (and in the fork, obviously). Summary: it is relatively easy to build but some minor changes to the code are required. Namely, the signals should be defined for Windows build and the MPI package does not work reliably when built for Windows (is the signal system not compatible at all?).

Cheers,
Mike

**Comment by cburstedde** [comment]
Thanks a lot. Let's see what we discuss in the pull request #26
