### ISSUE TITLE
quadrant_face_neighbor_extra does not change the tree index of the face neighbor

### ISSUE THREAD

**Issue by pytaunay** [cburstedde/p4est#29]
[step2.zip](https://github.com/cburstedde/p4est/files/1589456/step2.zip)
Hello,

I've been playing with the library for a bit and was trying to get the physical coordinates of all neighboring cells of a given quadrant in order to compute deltax or deltay for a finite difference scheme. 

I'm using p4est_iterate to go over all the available quadrants. Inside the callback function, I have a call to p4est_quadrant_face_neighbor_extra for each face of the quadrant to find the neighbors. I have noticed that neighbor_extra does find the correct neighboring tree number, but does not change it in the data field of the target quadrant (denoted "r" in the documentation). As a consequence, a subsequent call to p4est_quadrant_is_equal_piggy to compare the current quadrant to its neighbor will return true if the two quadrants are at the same level, even if they belong to different trees. 

A workaround is to set the .p.which_tree value of the neighbor quadrant to whatever p4est_quadrant_face_neighbor_extra returns.

I have attached a modified "p4est_step2" that implements a callback function "print_data". It prints the current quadrant location in physical space; then, for each neighboring face, it checks if the neighboring tree exists, checks if the quadrant returned by "neighbor_extra" is the same as the current quadrant, and prints the corresponding information. You can try this on the box.inp file, with a level 0 refinement to avoid cluttering the terminal. The output should be for example:

0,0,-3.000000,-1.000000,
0,0	 tn = -1? 1	 My tree id: 0	 My neighbor tree id: -1	 q = nq? 1
1,0	 tn = -1? 0	 My tree id: 0	 My neighbor tree id: 4	 q = nq? 1
2,0	 tn = -1? 0	 My tree id: 0	 My neighbor tree id: 2	 q = nq? 1
3,0	 tn = -1? 0	 My tree id: 0	 My neighbor tree id: 3	 q = nq? 1

which tells us that the quadrant 0 in the tree 0 has three neighboring trees (faces 1,2, and 3 with tn != -1). The neighbor quadrant is found to be identical to quadrant 0 (q = nq), even though they belong to different trees. Uncommenting line 125 in the attached source code fixes the problem, but it seemed to me that p4est_quadrant_face_neighbor_extra was supposed to change the data of the neighbor quadrant.

Am I misunderstanding the usage of p4est_quadrant_face_neighbor_extra? I'm also open to suggestions in finding "how far away" a neighboring cell is in physical space.

Thanks a lot!

**Comment by cburstedde** [comment]
You are right, we do not set the p member of the neighbor quadrant. We never do this for any p4est_quadrant_ function.

Usually we have the tree information available by context. If not, it helps to look at the code of face_neighbor_extra: You see how we check whether we are across a tree boundary or not. You can access tree_to_tree similarly to tree_to_face inside the function to get the tree number. I'm afraid you'd have to write your own function, but it should be very similar.
