### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by rubendibattista** [cburstedde/p4est#31]
Could you please upload the complete `tar.gz` (sc  and `.configure` included) on p4est.org? Or is it still not ready?

**Comment by cburstedde** [comment]
Yes I'm late on that. Will try to get to it.

**Comment by rubendibattista** [comment]
Thanks @cburstedde. I opened a PR for that.

**Comment by cburstedde** [comment]
I've followed your suggestion -- thanks!
