### ISSUE TITLE
p8est-test-loadsave failure

### ISSUE THREAD

**Issue by emvizible** [cburstedde/p4est#32]
Greetings --

Thanks for providing the p4est package! I'm installing this in our university cluster at CWRU, for a group wanting to run a geodynamics code that depends on dealii. My installation used the p4est-setup.sh, and I'm looking to clean up the install to correct a failure in the following test (all other tests passed):

test/p8est-test-loadsave.log
[libsc] This is libsc 1.1
[p4est] This is p4est 1.1
[libsc 1] Abort: Assertion 'p4est_is_valid (p4est)'
[libsc 1] Abort: /home/mrd20/src/rider/aspect-dep/p4est-1.1/src/p4est_io.c:264
[libsc 1] Abort: Obtained 10 stack frames
[libsc 1] Stack 0: libsc-1.1.so(sc_abort+0x2d) [0x7f166ce5b168]
[libsc 1] Stack 1: libsc-1.1.so(sc_abort_verbosef+0) [0x7f166ce5b397]
[libsc 1] Stack 2: libp4est-1.1.so(p8est_inflate+0xb46) [0x7f166d148d9e]
[libsc 1] Stack 3: libp4est-1.1.so(p8est_source_ext+0xb24) [0x7f166d0fcd89]
[libsc 1] Stack 4: libp4est-1.1.so(p8est_load_ext+0x91) [0x7f166d0fc220]
[libsc 1] Stack 5: libp4est-1.1.so(p8est_load+0x48) [0x7f166d0fc189]
[libsc 1] Stack 6: p8est_test_loadsave() [0x401a66]
[libsc 1] Stack 7: p8est_test_loadsave() [0x4021e8]
[libsc 1] Stack 8: libc.so.6(__libc_start_main+0xf5) [0x7f166bd20c05]
[libsc 1] Stack 9: p8est_test_loadsave() [0x401499]
[libsc 0] Abort: Assertion 'p4est_is_valid (p4est)'
[libsc 0] Abort: /home/mrd20/src/rider/aspect-dep/p4est-1.1/src/p4est_io.c:264
[libsc 0] Abort: Obtained 10 stack frames
[libsc 0] Stack 0: libsc-1.1.so(sc_abort+0x2d) [0x7f5292d29168]
[libsc 0] Stack 1: libsc-1.1.so(sc_abort_verbosef+0) [0x7f5292d29397]
[libsc 0] Stack 2: libp4est-1.1.so(p8est_inflate+0xb46) [0x7f5293016d9e]
[libsc 0] Stack 3: libp4est-1.1.so(p8est_source_ext+0xb24) [0x7f5292fcad89]
[libsc 0] Stack 4: libp4est-1.1.so(p8est_load_ext+0x91) [0x7f5292fca220]
[libsc 0] Stack 5: libp4est-1.1.so(p8est_load+0x48) [0x7f5292fca189]
[libsc 0] Stack 6: p8est_test_loadsave() [0x401a66]
[libsc 0] Stack 7: p8est_test_loadsave() [0x4021e8]
[libsc 0] Stack 8: libc.so.6(__libc_start_main+0xf5) [0x7f5291beec05]
[libsc 0] Stack 9: p8est_test_loadsave() [0x401499]
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[hpc3:150487] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[hpc3:150487] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

​Any guidance would be appreciated! I'll give some attention to p4est-io.c in the meantime.
Best wishes,
~ Emily​

**Comment by cburstedde** [comment]
Have you tried the latest master and/or develop version in a clean build?

If it still does not work, can you run the test by hand with mpirun -np x test/p8est_test_loadsave and see for which values of x it breaks?

**Comment by cburstedde** [comment]
Any news?

**Comment by cburstedde** [comment]
The test case works for me. Your error occurs on loading a file. Could you please attach the .p8p file that the test has written just before?
