### ISSUE TITLE
`refine_callback` in p4est_wrap

### ISSUE THREAD

**Issue by rubendibattista** [cburstedde/p4est#34]
Hello, 

I hope this is the right place where to ask questions.

I'm just starting up working with `p4est` and I was looking a bit to the `p4est_wrap` code. It is not really clear to me what is the purpose of the `p4est_wrap` interface. 

More specifically I was looking to the `p4est_wrap_adapt` that calls `p4est_refine_ext` with the `refile_callback` function defined at the top of `p4est_wrap.c`.

What I do not understand is what actually that function does. Because I see it editing some flags within the `*pp` struct, and returning a bit AND operation. But what I don't get is the big picture. How a user should interact with it? 

Thanks,

**Comment by cburstedde** [comment]
The p4est_wrap is a bit obscure and I do not recommend to use it in new code.
It tries to encapsulate some of the usual logic that an application needs when adapting the mesh.
I'd advise you to start fresh yourself -- nothing wrong with digging around in the wrap code, but I'd rather not support this functionality officially.
