### ISSUE TITLE
Needs help about install

### ISSUE THREAD

**Issue by tdphuongnttc** [cburstedde/p4est#35]
Hi, I had finisned basic installation in the file INSTALL, but when I try run
"Compilers and Options" and type ./configure CC=c99 CFLAGS=-g LIBS=-lposix
I still have the error?

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for a sed that does not truncate output... /bin/sed
checking Major version... 2
checking Minor version... 0
checking Point version... 2-a991
o---------------------------------------
| Checking options
o---------------------------------------
o---------------------------------------
| Checking MPI and related programs
o---------------------------------------
checking whether we are using MPI... no
checking whether we are using MPI I/O... no
checking whether we are using MPI_Init_thread... no
checking for gfortran... gfortran
checking for gfortran... gfortran
checking whether the Fortran 77 compiler works... no
**configure: error: in /home/peter/Downloads/p4est': configure: error: Fortran 77 compiler cannot create executables** 
Seeconfig.log' for more details

**Comment by tdphuongnttc** [comment]
Would you tell me more details? I mean that I need OpenMPI ?

**Comment by cburstedde** [comment]
Any progress?

**Comment by eliasstudiert** [comment]
> The dependency on fortran in the build process is some of the things I don't like very much. It came in due to libsc having some support for blas and lapack, and so far I have not managed to have the autotools not require a fortran compiler even --without-blas.
> 
> A quick fix would be to find the fortran compiler on your computer, or to install it (say gfortran), and to set F77=gfortran and/or MPIF77=mpif77 on the configure line. Note that the MPI installation needs to access the same fortran compiler than p4est. Let us know how it goes.

I had the same issue and installed gfortran. But could you please explain how to set F77=gfortran and/or MPIF77=mpif77 on the configure line? 
Best
Elias

**Comment by data-panda** [comment]
@eliasstudiert 

```shell
$ export F77=<path to gfortran>
$export MPIF77=<path to mif77>
```
and then run `./configure`. Hope this helps.

P.S.> replace <...> with the path to executable

**Comment by cburstedde** [comment]
Another way is to work with the branch prev3-develop. Fortran and blas have been removed.
