### ISSUE TITLE
How to compile new examples.

### ISSUE THREAD

**Issue by ztdepztdep** [cburstedde/p4est#36]
Dear group:
     I made some modification to the file p4est_step1 in the example directory. I use the following command to compile it:
    make p4est_step1
   make: *** No rule to make target 'p4est_step1'.  Stop.
   Could you please give me some suggestions.
Regards

**Comment by tdphuongnttc** [comment]
Do you follow steps in INSTALL file?

**Comment by ztdepztdep** [comment]
yes, I have compiled it successfully and run the example file successfully in the example directory. 
I want to compile its new version after a modification to the example 1. 
which command should i use.

**Comment by tdphuongnttc** [comment]
could I contact to you through your email? I need some helps about instruction.

**Comment by ztdepztdep** [comment]
what is your problems
Dear friends, do you have a fortram compiler installed in your system.




ztdepyahoo@163.com
 
From: tdphuongnttc
Date: 2018-04-08 21:10
To: cburstedde/p4est
CC: ztdepztdep; Author
Subject: Re: [cburstedde/p4est] How to compile new examples. (#36)
could I contact to you through your email? I need some helps about instruction.

**Comment by rubendibattista** [comment]
The p4est library is a C library, so you link it in the standard way, providing include files and library to the compiler/linker.

It would be useful to know your precise configuration, operating system, full procedure you are doing to compile, and full stdout/stderr log.

**Comment by cburstedde** [comment]
On Wed, Apr 11, 2018 at 03:20:27AM -0700, ztdepztdep wrote:
> Dear sir:
>      I i want to create a project of my own. How to link with the P4est library.

One way is this:

1. Do make install of p4est as in the INSTALL document, either by cloning from
   the repo or by unpacking the .tar.gz file.
2. Create a new directory for your project with a new Makefile.  In that
   Makefile, include the Makefile.p4est.mk from the etc/ directory of the p4est
   installation.  Use pre-defined variables / weak as necessary.

**Comment by ztdepztdep** [comment]
thank you very much. I am working with my new project now.
