### ISSUE TITLE
Let p4est_vtk_write_file output visit file only

### ISSUE THREAD

**Issue by ztdepztdep** [cburstedde/p4est#37]
Dear sir:
    I want to ouput the results in visit format only. It seems the function "p4est_vtk_write_file" output both visit and vtu format. 
   How to resolve it.
Regards

**Comment by cburstedde** [comment]
The data are written in the .vtu files, which visit is able to read. It should work fine as is.
If writing in parallel, you get one .vtu file per MPI rank. Then you also get meta-files .pvtu and .visit. You will see that they are just placeholders to reference the .vtu files. Visit should be able to read the .visit file. If not, feel free to submit a bug report and/or a pull request with a fix.

If you want to write a different file format entirely, feel free to start p4est_formatxyz.{c,h} files and write this yourself.
