### ISSUE TITLE
Is p4est_nodes mandatory requirement ?

### ISSUE THREAD

**Issue by data-panda** [cburstedde/p4est#40]
I am developing an application based on Finite Volume, for the creation and modification of forest I see "Into p4(8)est_nodes_new_local" and other stuff which consume a bit of compute time. I understand that the node information is required for Finite Element based application. Is there a way to turn it off or is it hard ingrained feature of the code.

**Comment by cburstedde** [comment]
No, it is not needed.
For finite volumes, you will only need face neighbors in p4est_balance and p4est_ghost, no edges and corners.
You can work directly with p4est_ghost, or you can look into p4est_iterate and learn to use it.

**Comment by cburstedde** [comment]
The new_local happens in VTK output depending on the parameters, not in the simulation itself.

**Comment by data-panda** [comment]
Hi Carsten,

The question was about the vtk writing module which triggers
"p4est_nodes_new_local" creation everytime while writing a vtk file. Is
there a way to circumvent the node creation/calculation everytime before
writing the vtk file. I am guessing it has to with geometrical calculation
for writing the cell extents in x,y and z coordinates. Could you please
clarify

---------------------------------

With thanks & regards

Aniruddha

**Comment by cburstedde** [comment]
The local node creation is very different from p4est_nodes_new. We use it for the corners of the VTK cubes to write. It is serial and has a run time linear in the number of elements.

I would not worry about it.
