### ISSUE TITLE
p4(8)est_ghost_** appears when the code is run on one processor

### ISSUE THREAD

**Issue by data-panda** [cburstedde/p4est#41]
I have compiled the p4est library with exact same setting on two machines ( --enable-mpi --enable-openmp --enable-pthread --prefix=/usr/local)
On machine A when I run the same code then I see this appearing during refinement/vtk writing process

--------------------------
[p4est] Done p8est_new with 262144 total quadrants
[p4est] Into p8est_nodes_new_local
[p4est] Done p8est_nodes_new_local
--------------------------

whereas on another machine I am getting 

--------------------------
[p4est] Done p8est_new with 262144 total quadrants
[p4est] Into p8est_nodes_new_local
[p4est] Into p8est_ghost_new CORNER
[p4est] Done p8est_ghost_new
[p4est] Done p8est_nodes_new_local
--------------------------

Surprisingly on both machines I am running it as one process. Annoying fact is that I have to spend time on the creation of ghost everytime I write the vtk files. What could be the reason.

PS. Running it as mpirun -np 1 ./a.out

**Comment by cburstedde** [comment]
> I have compiled the p4est library with exact same setting on two machines ( --enable-mpi --enable-openmp --enable-pthread --prefix=/usr/local)
> On machine A when I run the same code then I see this appearing during refinement/vtk writing process
> --------------------------
> [p4est] Done p8est_new with 262144 total quadrants
> [p4est] Into p8est_nodes_new_local
> [p4est] Done p8est_nodes_new_local
> --------------------------
> 
> whereas on another machine I am getting 
> --------------------------
> [p4est] Done p8est_new with 262144 total quadrants
> [p4est] Into p8est_nodes_new_local
> [p4est] Into p8est_ghost_new CORNER
> [p4est] Done p8est_ghost_new
> [p4est] Done p8est_nodes_new_local
> --------------------------
> 
> Surprisingly on both machines I am running it as one process. Annoying fact is that I have to spend time on the creation of ghost everytime I write the vtk files. What could be the reason.
> 
> PS. Running it as mpirun -np 1 ./a.out

I'd doubt that.  The second version is from --enable-debug, which calls
ghost_new_check.  It's not called in production code.

**Comment by data-panda** [comment]
thanks carsten indeed, the --enable-debug was left on in one of the installations.
