### ISSUE TITLE
p4est_iter_face_info at boundary

### ISSUE THREAD

**Issue by data-panda** [cburstedde/p4est#44]
The documentation of p4est_iter_face_info_t (face iterative callback) says -
```
/** The information that is available to the user-defined p4est_iter_face_t
 * callback.
 *
 * The orientation is 0 if the face is within one tree; otherwise, it is the
 * same as the orientation value between the two trees given in the
 * connectivity.  If the face is on the outside boundary of the forest, then
 * there is only one side.  If tree_boundary is false, the face is on the
 * interior of a tree.  When tree_boundary is false, sides[0] contains the
 * lowest z-order quadrant that touches the face.
 * When tree_boundary is true, its value is P4EST_CONNECT_FACE.
 */

typedef struct p4est_iter_face_info
{
  p4est_t            *p4est;
  p4est_ghost_t      *ghost_layer;
  int8_t              orientation; /**< the orientation of the sides to each
                                        other, as in the definition of
                                        p4est_connectivity_t */
  int8_t              tree_boundary; /**< boolean: interior face (0),
                                          boundary face (1) */
  sc_array_t          sides;    /* array of p4est_iter_face_side_t type */
}
p4est_iter_face_info_t;
```

Questions -
1. if the face is at the tree boundary and NOT at the forest boundary what is the value of `info->tree_boundary` 
2. I encounter a situation where for a boundary face (forest boundary), i have the value of `info->tree_boundary` as 31 which non zero but not 1 as stated in the documentation. Does 31 signify something or it can be any non-zero number for tree boundary.
3. If a face is **interior** then `sides` will have two sides whereas if a face is **exterior** the `sides` will have only one element. How does one check if a face is at the tree boundary BUT an interior face ?

**Comment by cburstedde** [comment]
1. and 2.: You're right, the docs were wrong. The value is P{4,8}EST_CONNECT_FACE.
  This is now fixed in the develop branch of p4est.
3.: If you check the number of sides first and find it to be 2, just write if (tree_boundary) { ... }.
