### ISSUE TITLE
Local p4est_nodes_new fails with quadrants at max level

### ISSUE THREAD

**Issue by oiffrig** [cburstedde/p4est#45]
Using `p4est_nodes_new` without ghosts fails when there are quadrants at level `P4EST_QMAXLEVEL` ; passing a ghost structure works though. The error message is:

> [libsc 0] Abort: Assertion '0 <= nlevel && nlevel <= P4EST_QMAXLEVEL'
> [libsc 0] Abort: src/p4est_nodes.c:79

See oiffrig/p4est@36900f9e764221f2cd8f7b49f8b833ce1c54279d for example code.

I have compiled p4est with `--enable-mpi --enable-debug`.

**Comment by oiffrig** [comment]
Did you compile with debugging turned on? I updated the issue with the compilation options.

**Comment by oiffrig** [comment]
Works for me. Thanks!
I have updated the fix-nodes-new-local branch on my fork with the test case and author information: oiffrig/p4est@25f5d3737e89c8ae9b569f28828e1bc91786fc51

**Comment by oiffrig** [comment]
Done. oiffrig/p4est@e68d1233f430d2c372ebe945af417378cad401a7

**Comment by cburstedde** [comment]
Thanks! I'll look into it soon to integrate the fix.

**Comment by cburstedde** [comment]
Thanks, merged into develop!
