### ISSUE TITLE
p4est_step2.c problem with .inp files generated by Gmsh

### ISSUE THREAD

**Issue by kwang2** [cburstedde/p4est#46]
Hello,

I was running the examples in the example/steps directory and got some problems with p4est_step2. It works pretty well when I used .inp files generated by cubit (hole_2d_cubit.inp and hole_3d_cubit.inp), but it failed when the .inp files generated by Gmsh (hole_2d_gmsh.inp and hole_3d_gmsh.inp) was given as the input. For example, when I ran "./p4est_step2 hole_2d_gmsh.inp 2", the error message was:

[p4est] This is the p4est 2D demo example/steps/p4est_step2
[p4est] Reading connectivity from hole_2d_gmsh.inp
[p4est 0] Encountered element that will not fit into tree_to_vertex array. More elements than expected.
[p4est 0] Failed to read hole_2d_gmsh.inp: pass 2
[p4est 0] Failed to read a valid connectivity from hole_2d_gmsh.inp
[libsc 0] Abort: Obtained 4 stack frames
[libsc 0] Stack 0: p4est_step2() [0x45548b]
[libsc 0] Stack 1: p4est_step2() `[0x402a57]`
[libsc 0] Stack 2: libc.so.6(__libc_start_main+0xf5) [0x2b08cb7733d5]
[libsc 0] Stack 3: p4est_step2() [0x4027b9]
[unset]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

I found the error was generated by the function p4est_connectivity_read_inp_stream in p4est_connectivity.h.

From line 4352 - 4360:
```C
        retval = sscanf (line, "%lld, %lld, %lld, %lld, %lld"
#ifdef P4_TO_P8
                         ", %lld, %lld, %lld, %lld"
#endif
                         , &element_number, &v[0], &v[1], &v[3], &v[2]
#ifdef P4_TO_P8
                         , &v[4], &v[5], &v[7], &v[6]
#endif
          );
```

Here `element_number` is read directly from the .inp file. However, `element_number` may start from 1 like in hole_2d_cubit.inp, or may not start from 1 like in hole_2d_gmsh.inp. When it does not start from 1, it would cause the conditional in Line 4367 `element_number > *num_trees` to be evaluated as true and the code would fail.

I added a variable `element_number_read` to record the number of elements that have been read and the code seems working fine.

```C
int
p4est_connectivity_read_inp_stream (FILE * stream,
                                    p4est_topidx_t * num_vertices,
                                    p4est_topidx_t * num_trees,
                                    double *vertices,
                                    p4est_topidx_t * tree_to_vertex)
{
  int                 reading_nodes = 0, reading_elements = 0;
  int                 lines_read = 0, lines_free = 0;
  char               *line;
  p4est_topidx_t      num_nodes = 0;
  p4est_topidx_t      num_elements = 0;
  int                 fill_trees_and_vertices = (vertices != NULL &&
                                                 tree_to_vertex != NULL);
  long long int       element_number_read = 0;

  P4EST_ASSERT ((vertices == NULL && tree_to_vertex == NULL) ||
                (vertices != NULL && tree_to_vertex != NULL));

  for (;;) {
    line = p4est_connectivity_getline_upper (stream);

    if (line == NULL) {
      break;
    }

    ++lines_read;

    /* check for control line */
    if (line[0] == '*') {
      reading_elements = reading_nodes = 0;
      if (strstr (line, "*NODE")) {
        reading_nodes = 1;
        ++lines_free;
        P4EST_FREE (line);
        continue;
      }
      else if (strstr (line, "*ELEMENT")) {
        if (
#ifdef P4_TO_P8
             strstr (line, "TYPE=C3D8")
#else
             strstr (line, "TYPE=C2D4") || strstr (line, "TYPE=CPS4")
             || strstr (line, "TYPE=S4")
#endif
          ) {
          reading_elements = 1;
          ++lines_free;
          P4EST_FREE (line);
	  element_number_read = 0;
          continue;
        }
      }
    }

    if (reading_nodes) {
      if (fill_trees_and_vertices) {
        long long int       node;
        double              x, y, z;
        int                 retval;

        retval = sscanf (line, "%lld, %lf, %lf, %lf", &node, &x, &y, &z);
        if (retval != 4) {
          P4EST_LERROR ("Premature end of file");
          P4EST_FREE (line);
          return 1;
        }

        if (node > *num_vertices) {
          P4EST_LERRORF
            ("Encountered vertex %lld that will not fit in vertices"
             " array of length %lld.  Are the vertices contiguously"
             " numbered?\n", node, (long long int) *num_vertices);
          P4EST_FREE (line);
          return 1;
        }

        vertices[3 * (node - 1) + 0] = x;
        vertices[3 * (node - 1) + 1] = y;
        vertices[3 * (node - 1) + 2] = z;
      }

      ++num_nodes;
    }
    else if (reading_elements) {
      if (fill_trees_and_vertices) {
        long long int       element_number;
        long long int       v[P4EST_CHILDREN];
        int                 n;
        int                 retval;

        /* Note that when we read in the
         * vertices we switch from right-hand
         * vertex ordering to z-order
         */
        retval = sscanf (line, "%lld, %lld, %lld, %lld, %lld"
#ifdef P4_TO_P8
                         ", %lld, %lld, %lld, %lld"
#endif
                         , &element_number, &v[0], &v[1], &v[3], &v[2]
#ifdef P4_TO_P8
                         , &v[4], &v[5], &v[7], &v[6]
#endif
          );
        if (retval != P4EST_CHILDREN + 1) {
          P4EST_LERROR ("Premature end of file");
          P4EST_FREE (line);
          return 1;
        }
	
	++element_number_read;

        //if (element_number > *num_trees) {
	if (element_number_read > *num_trees) {
          P4EST_LERROR ("Encountered element that will not fit into"
                        " tree_to_vertex array. More elements than expected.\n");
          P4EST_FREE (line);
          return 1;
        }

        for (n = 0; n < P4EST_CHILDREN; ++n)
          //tree_to_vertex[P4EST_CHILDREN * (element_number - 1) + n] =
	  tree_to_vertex[P4EST_CHILDREN * (element_number_read - 1) + n] =
            v[n] - 1;
      }

      ++num_elements;
    }

    ++lines_free;
    P4EST_FREE (line);
  }

  *num_vertices = num_nodes;
  *num_trees = num_elements;

  if (num_nodes == 0 || num_elements == 0) {
    P4EST_LERROR ("No elements or nodes found in mesh file.\n");
    return -1;
  }
  else {
    return 0;
  }
}
```

Since the tutorial p4est-howto.pdf used hole_3d_gmsh.inp as an example, I was wondering whether this is a bug introduced in a later version. Please verify. Thank you!

**Comment by lcw** [comment]
Hi @kwang2, thanks for finding the issue.  You are indeed correct that something changed along the way.  At some point we decided to respect the element number in the inp file, see ea5f86e5c22f98f0260f927cb43a686317805304.  This seems to work for cubit files but not Gmsh files.  So I think we should fix it but I am not sure exactly how as sometimes it is nice to preserve the numbering of the trees.  I am open to suggestions.  @cburstedde do you have any ideas?

**Comment by lcw** [comment]
After thinking about it I am not sure we even know the elements are going to be contiguously numbered.  So I think we should revert ea5f86e5c22f98f0260f927cb43a686317805304.  @cburstedde can you please revert this change on the develop branch?

**Comment by cburstedde** [comment]
> After thinking about it I am not sure we even know the elements are going to be contiguously numbered.  So I think we should revert ea5f86e5c22f98f0260f927cb43a686317805304.  @cburstedde can you please revert this change on the develop branch?

Done.  Does the current develop work for y'all?

**Comment by lcw** [comment]
Thanks @cburstedde, seems to work for me.  How about you @kwang2?

**Comment by kwang2** [comment]
It works perfectly. Thank you very much! @lcw @cburstedde
