### ISSUE TITLE
Possible bug with vtk vector data in 2D

### ISSUE THREAD

**Issue by data-panda** [cburstedde/p4est#47]
Well in 2D the vector length should be 2 

**p4est_vtk.c:1113** reads
```
SC_CHECK_ABORT (values[all]->elem_count ==
                    3 * (size_t) cont->p4est->local_num_quadrants,
                    P4EST_STRING
                    "_vtk: Error: incorrect cell vector data count; vector data must contain exactly 3*p4est->local_num_quadrants doubles.");
```

I think this needs to be replaced by 
```
SC_CHECK_ABORT (values[all]->elem_count ==
                    P4EST_DIM * (size_t) cont->p4est->local_num_quadrants,
                    P4EST_STRING
                    "_vtk: Error: incorrect cell vector data count; vector data must contain exactly 3*p4est->local_num_quadrants doubles.");
```

**Comment by data-panda** [comment]
I looked into the vtk format and it seems the vector length must be 3 even if it is a 2D vector. So one has to allocate memory for the third dimension as well and then set it explicitly to ZERO. Correct me if i have got it wrong.

The issue may be closed after any comments.

**Comment by cburstedde** [comment]
> I looked into the vtk format and it seems the vector length must be 3 even if it is a 2D vector. So one has to allocate memory for the third dimension as well and then set it explicitly to ZERO. Correct me if i have got it wrong.

Yes, this is one reason.  The other is that our 2D forest may be a manifold
embedded in a 3D, where 3-vectors make sense.

**Comment by data-panda** [comment]
Thanks Carsten for the clarification. I now do get the second reason as well.
