### ISSUE TITLE
Do the project have the plan of anisotropic mesh refinement ?

### ISSUE THREAD

**Issue by LucienPan0903** [cburstedde/p4est#49]

**Comment by data-panda** [comment]
Hi Jianhua,

Have you looked at the *p6est* module of the p4est library. I think it
has features for "anisotropic refinement".

You can also have a look at this https://arxiv.org/pdf/1406.6573.pdf
<https://arxiv.org/pdf/1406.6573.pdf>

---------------------------------

With thanks & regards

*Aniruddha*

**Comment by LucienPan0903** [comment]
@data-panda Thank you very much! I realized that just the moment I submitted this issure :). p6est is right what I need.
