### ISSUE TITLE
Does p4est suppport curved boundary.

### ISSUE THREAD

**Issue by ztdepztdep** [cburstedde/p4est#51]
Dear sir:
      When p4est refine the grid, does it treat the curved boundary. 
Regards

**Comment by cburstedde** [comment]
>       When p4est refine the grid, does it treat the curved boundary. 

While it is true that we store world coordinates for tree vertices, which can
be interpolated to quadrant coordinates within a tree, this is just a
convenience.

You are free to implement any geometry, curved or not, in your code.  One way
to do it is to formulate a map from the tree world coordinates to the space of
your application.  If you rather work with isoparametric geometries, please
consider using the p4est_lnodes data structure for your geometry to avoid holes
at hanging nodes.

**Comment by ztdepztdep** [comment]
> When p4est refine the grid, does it treat the curved boundary.
> While it is true that we store world coordinates for tree vertices, which can be interpolated to quadrant coordinates within a tree, this is just a convenience. You are free to implement any geometry, curved or not, in your code. One way to do it is to formulate a map from the tree world coordinates to the space of your application. If you rather work with isoparametric geometries, please consider using the p4est_lnodes data structure for your geometry to avoid holes at hanging nodes.

Thank you for your feedback. I want to use it in my fluid flow with FVM. Let me study your code further.

**Comment by vryy** [comment]
> You are free to implement any geometry, curved or not, in your code. One way to do it is to formulate a map from the tree world coordinates to the space of your application. If you rather work with isoparametric geometries, please consider using the p4est_lnodes data structure for your geometry to avoid holes at hanging nodes.

While this approach is very reasonable mathematically, it is difficult in practice to implement a map from the reference space to arbitrary geometry. Would it be possible to provide a callback function to p4est_qcoord_to_vertex to automatically modify the nodal coordinates based on curve boundary?

**Comment by cburstedde** [comment]
> > You are free to implement any geometry, curved or not, in your code. One way to do it is to formulate a map from the tree world coordinates to the space of your application. If you rather work with isoparametric geometries, please consider using the p4est_lnodes data structure for your geometry to avoid holes at hanging nodes.
> 
> While this approach is very reasonable mathematically, it is difficult in practice to implement a map from the reference space to arbitrary geometry. Would it be possible to provide a callback function to p4est_qcoord_to_vertex to automatically modify the nodal coordinates based on curve boundary?

p4est_qcoord_to_vertex is not used within p4est except in p4est_plex (and
p4est_wrap, but its use is discouraged).  Mapping is a functionality that is
irrelevant to p4est's purpose, and we leave it to the user's application.

You can use p4est_qcoord_to_vertex as a first step in your mapping and compose
it with a function of your own, but you don't need to use it.  You can use the
vertex information in the connectivity, but you do not need to.  Again, p4est
does not call this function; mapping lies entirely on the application side.

The VTK function takes an optional geometry pointer in which you can place a
callback, but this is just for a convenient display of maps.
