### ISSUE TITLE
p4est_iterate function is different from its definition in the help file.

### ISSUE THREAD

**Issue by ztdepztdep** [cburstedde/p4est#52]
Dear sir: 
   I the step3, the p4est_iterate is used as:
```
    p4est_iterate (p4est, NULL,   /* we don't need any ghost quadrants for this loop */
                (void *) T,     /* pass in u_interp so that we can fill it */
                step3_interpolate_solution,    /* callback function that interpolates from the cell center to the */
                NULL,          /* there is no callback for the faces between quadrants */
                NULL);         /* there is no callback for the corners between quadrants */
```
 But in the documentation file, it is defined as:
```
  void p4est_iterate | ( | p4est_t * | p4est,
  p4est_ghost_t * | ghost_layer,
  void * | user_data,
  p4est_iter_volume_t | iter_volume,
  p4est_iter_face_t | iter_face,
  p4est_iter_corner_t | iter_corner
  )
```
      Could you please give me some suggestions.
Regards

**Comment by cburstedde** [comment]
>    I the step3, the p4est_iterate is used as:
> ```
>     p4est_iterate (p4est, NULL,   /* we don't need any ghost quadrants for this loop */
>                 (void *) T,     /* pass in u_interp so that we can fill it */
>                 step3_interpolate_solution,    /* callback function that interpolates from the cell center to the */
>                 NULL,          /* there is no callback for the faces between quadrants */
>                 NULL);         /* there is no callback for the corners between quadrants */
> ```
>  But in the documentation file, it is defined as:
> ```
>   void p4est_iterate | ( | p4est_t * | p4est,
>   p4est_ghost_t * | ghost_layer,
>   void * | user_data,
>   p4est_iter_volume_t | iter_volume,
>   p4est_iter_face_t | iter_face,
>   p4est_iter_corner_t | iter_corner
>   )
> ```
>       Could you please give me some suggestions.

Some of the pointers are allowed to be NULL.  Please see the comments in the .h
files.  The most common use of iterate uses a non-NULL ghost and one or more
non-NULL callback functions.
