### ISSUE TITLE
p4est fails with --enable-openmp

### ISSUE THREAD

**Issue by teamblubee** [cburstedde/p4est#53]
I am building p4est but the build fails with these errors

```shell
if (target_option=k; case ${target_option-} in ?) ;; *) echo "am__make_running_with_option: internal error: invalid" "target option '${target_option-}' specified" >&2; exit 1;; esac; has_opt=no; sane_makeflags=$MAKEFLAGS; if { if test -z '0'; then false; elif test -n 'amd64-portbld-freebsd12.0'; then true; elif test -n '4.2.1' && test -n '/wrkdirs/usr/ports/math/p4est/work/p4est-0f856ec463d506457645ba47924ef4a285de754e'; then true; else false; fi; }; then sane_makeflags=$MFLAGS; else case $MAKEFLAGS in *\\[\ \	]*) bs=\\; sane_makeflags=`printf '%s\n' "$MAKEFLAGS" | sed "s/$bs$bs[$bs $bs	]*//g"`;; esac; fi; skip_next=no; strip_trailopt () { flg=`printf '%s\n' "$flg" | sed "s/$1.*$//"`; }; for flg in $sane_makeflags; do test $skip_next = yes && { skip_next=no; continue; }; case $flg in *=*|--*) continue;; -*I) strip_trailopt 'I'; skip_next=yes;; -*I?*) strip_trailopt 'I';; -*O) strip_trailopt 'O'; skip_next=yes;; -*O?*) strip_trailopt 'O';; -*l) strip_trailopt 'l'; skip_next=yes;; -*l?*) strip_trailopt 'l';; -[dEDm]) skip_next=yes;; -[JT]) skip_next=yes;; esac; case $flg in *$target_option*) has_opt=yes; break;; esac; done; test $has_opt = yes); then \
  failcom='fail=yes'; \
else \
  failcom='exit 1'; \
fi; \
dot_seen=no; \
target=`echo all-recursive | sed s/-recursive//`; \
case "all-recursive" in \
  distclean-* | maintainer-clean-*) list='sc' ;; \
  *) list='sc' ;; \
esac; \
for subdir in $list; do \
  echo "Making $target in $subdir"; \
  if test "$subdir" = "."; then \
    dot_seen=yes; \
    local_target="$target-am"; \
  else \
    local_target="$target"; \
  fi; \
  (CDPATH="${ZSH_VERSION+.}:" && cd $subdir && gmake  $local_target) \
  || eval $failcom; \
done; \
if test "$dot_seen" = "no"; then \
  gmake  "$target-am" || exit 1; \
fi; test -z "$fail"
Making all in sc
gmake[1]: Entering directory '/wrkdirs/usr/ports/math/p4est/work/p4est-0f856ec463d506457645ba47924ef4a285de754e/sc'
gmake[1]: Nothing to be done for 'all'.
gmake[1]: Leaving directory '/wrkdirs/usr/ports/math/p4est/work/p4est-0f856ec463d506457645ba47924ef4a285de754e/sc'
gmake[1]: Entering directory '/wrkdirs/usr/ports/math/p4est/work/p4est-0f856ec463d506457645ba47924ef4a285de754e'
Makefile:3180: update target 'example/mesh/mesh2.o' due to: example/mesh/mesh2.c example/mesh/.dirstamp example/mesh/.deps/.dirstamp
depbase=`echo example/mesh/mesh2.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
cc -DHAVE_CONFIG_H -I. -I./src  -I./src -Isc/src -I./sc/src -O2 -pipe  -I/usr/local/include -I/usr/local/flang/include -I/usr/local/llvm60/include -I/usr/local/llvm60/lib/clang/6.0.1/include -fstack-protector -fno-strict-aliasing -I/usr/local/include  -O2 -pipe  -I/usr/local/include -I/usr/local/flang/include -I/usr/local/llvm60/include -I/usr/local/llvm60/lib/clang/6.0.1/include -fstack-protector -fno-strict-aliasing -fopenmp -MT example/mesh/mesh2.o -MD -MP -MF $depbase.Tpo -c -o example/mesh/mesh2.o example/mesh/mesh2.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from example/mesh/mesh2.c:37:
In file included from ./src/p4est_bits.h:35:
In file included from ./src/p4est.h:45:
./src/p4est_connectivity.h:551:49: error: unknown type name 'MPI_Comm'
void                p4est_connectivity_reorder (MPI_Comm comm, int k,
                                                ^
1 error generated.
gmake[1]: *** [Makefile:3180: example/mesh/mesh2.o] Error 1
gmake[1]: Leaving directory '/wrkdirs/usr/ports/math/p4est/work/p4est-0f856ec463d506457645ba47924ef4a285de754e'
```

The function MPI_Comm is defined in mpi.h located in /usr/local.

Is this a problem with openmpi, do I need to build with mpich?

**Comment by cburstedde** [comment]
It seems you're using metis without mpi.  We had not tested the compile for
this combination.  It is fixed on the develop branch now.  Can you try again?

Thanks for the report!

**Comment by teamblubee** [comment]
> It seems you're using metis without mpi. We had not tested the compile for this combination. It is fixed on the develop branch now. Can you try again? Thanks for the report!
> […](#)
> I am building p4est but the build fails with these errors ```shell if (target_option=k; case ${target_option-} in ?) ;; *) echo "am__make_running_with_option: internal error: invalid" "target option '${target_option-}' specified" >&2; exit 1;; esac; has_opt=no; sane_makeflags=$MAKEFLAGS; if { if test -z '0'; then false; elif test -n 'amd64-portbld-freebsd12.0'; then true; elif test -n '4.2.1' && test -n '/wrkdirs/usr/ports/math/p4est/work/p4est-0f856ec463d506457645ba47924ef4a285de754e'; then true; else false; fi; }; then sane_makeflags=$MFLAGS; else case $MAKEFLAGS in *\\[\ \ ]*) bs=\\; sane_makeflags=`printf '%s\n' "$MAKEFLAGS" | sed "s/$bs$bs[$bs $bs ]*//g"`;; esac; fi; skip_next=no; strip_trailopt () { flg=`printf '%s\n' "$flg" | sed "s/$1.*$//"`; }; for flg in $sane_makeflags; do test $skip_next = yes && { skip_next=no; continue; }; case $flg in *=*|--*) continue;; -*I) strip_trailopt 'I'; skip_next=yes;; -*I?*) strip_trailopt 'I';; -*O) strip_trailopt 'O'; skip_next=yes;; -*O?*) strip_trailopt 'O';; -*l) strip_trailopt 'l'; skip_next=yes;; -*l?*) strip_trailopt 'l';; -[dEDm]) skip_next=yes;; -[JT]) skip_next=yes;; esac; case $flg in *$target_option*) has_opt=yes; break;; esac; done; test $has_opt = yes); then \ failcom='fail=yes'; \ else \ failcom='exit 1'; \ fi; \ dot_seen=no; \ target=`echo all-recursive | sed s/-recursive//`; \ case "all-recursive" in \ distclean-* | maintainer-clean-*) list='sc' ;; \ *) list='sc' ;; \ esac; \ for subdir in $list; do \ echo "Making $target in $subdir"; \ if test "$subdir" = "."; then \ dot_seen=yes; \ local_target="$target-am"; \ else \ local_target="$target"; \ fi; \ (CDPATH="${ZSH_VERSION+.}:" && cd $subdir && gmake $local_target) \ || eval $failcom; \ done; \ if test "$dot_seen" = "no"; then \ gmake "$target-am" || exit 1; \ fi; test -z "$fail" Making all in sc gmake[1]: Entering directory '/wrkdirs/usr/ports/math/p4est/work/p4est-0f856ec463d506457645ba47924ef4a285de754e/sc' gmake[1]: Nothing to be done for 'all'. gmake[1]: Leaving directory '/wrkdirs/usr/ports/math/p4est/work/p4est-0f856ec463d506457645ba47924ef4a285de754e/sc' gmake[1]: Entering directory '/wrkdirs/usr/ports/math/p4est/work/p4est-0f856ec463d506457645ba47924ef4a285de754e' Makefile:3180: update target 'example/mesh/mesh2.o' due to: example/mesh/mesh2.c example/mesh/.dirstamp example/mesh/.deps/.dirstamp depbase=`echo example/mesh/mesh2.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\ cc -DHAVE_CONFIG_H -I. -I./src -I./src -Isc/src -I./sc/src -O2 -pipe -I/usr/local/include -I/usr/local/flang/include -I/usr/local/llvm60/include -I/usr/local/llvm60/lib/clang/6.0.1/include -fstack-protector -fno-strict-aliasing -I/usr/local/include -O2 -pipe -I/usr/local/include -I/usr/local/flang/include -I/usr/local/llvm60/include -I/usr/local/llvm60/lib/clang/6.0.1/include -fstack-protector -fno-strict-aliasing -fopenmp -MT example/mesh/mesh2.o -MD -MP -MF $depbase.Tpo -c -o example/mesh/mesh2.o example/mesh/mesh2.c &&\ mv -f $depbase.Tpo $depbase.Po In file included from example/mesh/mesh2.c:37: In file included from ./src/p4est_bits.h:35: In file included from ./src/p4est.h:45: ./src/p4est_connectivity.h:551:49: error: unknown type name 'MPI_Comm' void p4est_connectivity_reorder (MPI_Comm comm, int k, ^ 1 error generated. gmake[1]: *** [Makefile:3180: example/mesh/mesh2.o] Error 1 gmake[1]: Leaving directory '/wrkdirs/usr/ports/math/p4est/work/p4est-0f856ec463d506457645ba47924ef4a285de754e' ``` The function MPI_Comm is defined in mpi.h located in /usr/local. Is this a problem with openmpi, do I need to build with mpich? -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #53

I can confirm that the development branch tag: 00da6a98a36c08833bb43eaf9d8f457ce587a3f2 does indeed fix the problem.

Since you mention metis, I hope asking here isn't going too far but I have a few patches for metis 5.1.0 to allow it to pick up local includes to properly detect prce headers and a few GKlib patches.

The Install.rst in the source folder says patches are welcomed but the metis forums and flyspray bug tracker seems inactive.
Where could I submit those patches?

**Comment by cburstedde** [comment]
I don't know about metis development.
Great the p4est fix works for you.
