### ISSUE TITLE
how to know the cell center coordinates in the complex geometry.

### ISSUE THREAD

**Issue by ztdepztdep** [cburstedde/p4est#54]
Dear professor:
     I have learned how to get the cell center coordinates in the "cube geometry". But how to know its values if the geometry is curved, for example, in step2 example.  which function should i use.
   Regards

**Comment by cburstedde** [comment]
You'd have to implement a function that maps coordinates of a cubic quadrant into real space in a curved way. For displaying with VTK, you may use the p4est_geometry structure to hold the function.
How the function works internally is up to you.
One way of ensuring continuity of the geometry is to use p4est_lnodes to number the nodes of the mesh and help you interpolate the geometry at hanging nodes/edges/faces.
