### ISSUE TITLE
Loop over corner nodes and volumes in the ghost layer.

### ISSUE THREAD

**Issue by JortJacobs** [cburstedde/p4est#55]
Can you extend the functionality of the iterate functions such that you can loop over corner nodes and volumes in the ghost layer?

User example:
1. Stream population across the grid.
2. Compute local quantities of interest based on the local population.
3. Compute spatial derivative of these quantities. 

Since MPI communication step is the bottleneck, I want to avoid communication steps as much as possible --> if I can loop over volumes in the ghost layer I can compute their quantities of interest locally and I do not have to include those quantities in the ghost layer information to compute the derivatives.

**Comment by cburstedde** [comment]
If you want to touch corners and edges that are not adjacent to local cells, just to the ghost layer, this would have to be added to the code. We're not working on this currently.
If you feel to write an extended p4est_iterate, that could be fun.
Note that you may get there faster by writing a simple top-down iterate from scratch using the split_array functionality. The current version is long, difficult and heavily optimized on the inside.

**Comment by cburstedde** [comment]
Corners and edges of ghost cells that do not touch the local partition have incomplete information on their respective neighbors and hanging status. You can obtain this information by p4est_ghost_expand, which adds a second layer of ghost quadrants.
