### ISSUE TITLE
Bug in p4est_vtk.c:p4est_vtk_write_cell_datav:Line 1063 

### ISSUE THREAD

**Issue by mounder21** [cburstedde/p4est#56]
Hi Carsten,
This's a bug in the p4est_vtk_write_cell_datav function:
Line 1063 should be moved to (assigned at) Line 1121.
    p4est_vtk_context_t *end = va_arg (ap, p4est_vtk_context_t *);  

//Fix
//Line 1063:  
  p4est_vtk_context_t *end;
//Line 1121: 
  end = va_arg (ap, p4est_vtk_context_t *);  

This issue is related to issue #47.
This correction will make the function consistent with p4est_vtk_write_point_datav (line 910).

**Comment by mounder21** [comment]
This issue is addressed in #50 which is has a pull request pending. Closing.

**Comment by cburstedde** [comment]
> This issue is addressed in #50 which is has a pull request pending. Closing. 

Thanks for the report!  I'd rediscovered this independently and fixed it.
P. also fixed it earlier, but I didn't get to merge it back then.
