### ISSUE TITLE
OpenMP Parallelism for Volume Iterate

### ISSUE THREAD

**Issue by data-panda** [cburstedde/p4est#57]
I understand that the p4est_iterate() call is a generic interator for a forest with custom call back functions for volume,face,edge,corner (either one or more combination from this). In one of the compute intensive applications I am using only the volume callback and thus would expect to iterate over the forest using multiple threads. Is is it possible to do it with the custom p4est_iterate or p4est_iterate_ext or do i need to write a loop iterating over all the quadrants of all the trees and then put this loop in a `#pragma omp parallel` directive ?

**Comment by cburstedde** [comment]
I wouldn't rely on any of the p4est functions to support a parallel for. Often, we use the loop increment to count variables, which is not compatible with out-of-order execution.

In the case of quadrant iteration over a volume, you can implement this yourself by copying the two nested loops (trees/quadrants) and modifying.
