### ISSUE TITLE
problems when installing with intelmpi compilers

### ISSUE THREAD

**Issue by francesco-magaletti** [cburstedde/p4est#58]
Dear developers,
I'm having trouble when installing p4est --enable-mpi when using intelmpi compilers. Actually I had also the same issue with recent openmpi version ( > 1.10). The error is always the same:
"checking compile/link for MPI C program... failed
configure: error: MPI C test failed"
Have you got any idea to solve the problem? 
Thank you,
Francesco

**Comment by cburstedde** [comment]
Are the mpicc executables etc. in your path? You can try to export MPICC=... and try again.
Try to examine the config.log file, it gives you details about the tests that failed and error messages.

**Comment by francesco-magaletti** [comment]
Yes they seem to be there, correctly. The ambient variables are correct, too ...
here some extracts from the config.log

configure:3914: checking whether we are using MPI
configure:3916: result: yes
configure:3933: checking whether we are using MPI I/O
configure:3935: result: yes
configure:3952: checking whether we are using MPI_Init_thread
configure:3954: result: yes
configure:3964: checking for mpiexec
configure:3980: found /opt/compilers/intel/pe-xe-2017/binary/impi/2017.3.196/bin64/mpiexec
configure:3991: result: mpiexec
configure:4028:                             F77 set to ifort
configure:4035:                              FC set to ifort
configure:4041:                              CC set to icc
configure:4047:                             CXX set to icpc
...

configure:4561: checking whether we are using the GNU Fortran 77 compiler
configure:4574: ifort -c  conftest.F >&5
conftest.F(3): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: => = . [ % ( :
       choke me
---------------^
compilation aborted for conftest.F (code 1)
configure:4574: $? = 1
configure: failed program was:
|       program main
| #ifndef __GNUC__
|        choke me
| #endif
|
|       end
configure:4583: result: no
.....

configure:7953: checking compile/link for MPI C program
configure:7988: icc -o conftest -O2 -DSC_LOG_PRIORITY=SC_LP_ESSENTIAL  conftest.c  >&5
conftest.c(33): catastrophic error: cannot open source file "mpi.h"
  #include <mpi.h>
                  ^

compilation aborted for conftest.c (code 4)
configure:7988: $? = 4
configure: failed program was:
| /* confdefs.h */
...

what do you think about it?

**Comment by data-panda** [comment]
Hi,

It seems to me that the environment variables are not set properly since it is using `icc` instead of `mpiicc` for checking the MPI. 

Before configuring try this on shell
`export CC=mpiicc`
`export CXX=mpiicpc`
`export F77=mpiifort`

And then run `./configure`. Also make sure the intelmpi module is loaded before you compile which you can test for yourself by running `mpiicc --version` on the shell before running `./configure`

**Comment by francesco-magaletti** [comment]
Thank you very much. This solves the problem! the mpi compilers were in MPICC but non in CC
