### ISSUE TITLE
spatial derivatives

### ISSUE THREAD

**Issue by ActarusG69** [cburstedde/p4est#60]
Hi,

First of all thanks for the effort.
I am able to construct a locally refined mesh for SMR applications.
Is there a simple (or almost simple) way, when iterating over quadrants, to compute the 3D gradients of a  cell center located variable and using the local value and the 26 neighbors variable values.
At least can you please give me indications as a  starting point.

Best.

**Comment by ActarusG69** [comment]
Hello,

I saw that  p8est_mesh_t enables to loop over face neighbors. I also saw that it is possible to loop over corner neighbors but I did not see anything concerning edge neighbors. Is this on purpose?
By the way, if this isn't implemented, do you recommend to loop over neighbors of neighbors?

Regards.

**Comment by cburstedde** [comment]
The logic on edge neighbors is work in progress. It is fairly close to finished, but I'll have to coordinate with the developers.

About neighbors of neighbors, check out ghost_expand (). You can work with this ghost structure yourself, but iterate () will not support the additional ghost cells.

**Comment by ActarusG69** [comment]
Thanks for your answer. I managed to do something by myself even though it is really dirty coding...

I have a last problem: how to get access to the id of the siblings of a fine cell located in the ghost region and that have the same coarse neighbor cell as the fine cell ?

**Comment by cburstedde** [comment]
> Thanks for your answer. I managed to do something by myself even though it is really dirty coding...
> 
> I have a last problem: how to get access to the id of the siblings of a fine cell located in the ghost region and that have the same coarse neighbor cell as the fine cell ?

We do not record ghost neighbors of ghost elements.  You could construct and
search such a cell or use more advanced top-down traversal techniques as
described in the 2015 paper for the ghost and iterate algorithms.

**Comment by cburstedde** [comment]
I have now published the feature-mesh-edge branch. You're welcome to try our edge encoding in the mesh structure, and we'll appreciate you feedback.
