### ISSUE TITLE
provide bootstrapped release tarballs

### ISSUE THREAD

**Issue by tjhei** [cburstedde/p4est#61]
Would you mind providing release tarballs that contain ``./configure``? You can upload them inside the github release for example.
Note that http://www.p4est.org/ still links to http://p4est.github.io/release/p4est-2.0.tar.gz

**Comment by lcw** [comment]
What doesn't work for you?  I just tried
```
curl -O http://p4est.github.io/release/p4est-2.0.tar.gz
tar xzvf p4est-2.0.tar.gz
cd p4est-2.0/
./configure
```
and it works here.

**Comment by tjhei** [comment]
> What doesn't work for you?

I am talking about v2.2:
1. There is no http://p4est.github.io/release/p4est-2.2.tar.gz
2. The .tar.gz at https://github.com/cburstedde/p4est/releases/tag/v2.2 are just a snapshot of the git repo and don't contain the bootstrapped files.

**Comment by lcw** [comment]
Ah thanks for pointing that out.  Now http://p4est.github.io/release/p4est-2.1.tar.gz and http://p4est.github.io/release/p4est-2.2.tar.gz have been added.  Please let us know if you have issues with them.

@cburstedde will have to change the website to point to the latest release.

**Comment by tjhei** [comment]
> Please let us know if you have issues with them.

v2.2 seems to work perfectly, thanks! :+1:

**Comment by cburstedde** [comment]
> Ah thanks for pointing that out.  Now http://p4est.github.io/release/p4est-2.1.tar.gz and http://p4est.github.io/release/p4est-2.2.tar.gz have been added.  Please let us know if you have issues with them.
> 
> @cburstedde will have to change the website to point to the latest release.

It's done, thanks Lucas for uploading the tarballs!
