### ISSUE TITLE
Query the neighborhood of a given position

### ISSUE THREAD

**Issue by data-panda** [cburstedde/p4est#64]
Given that I know the location of a point in space, P = (x,y,z) and say I want to interpolate the value of a scalar from cells around this point P, then is there some functionality builtin or if not then any suggestions on how to do this? To keep things simple let's assume there is no MPI parallelism.

A similar problem of this in a conventional cartesian grid would necessitate finding the `i,j,k` in which the point P resides and then use `i+1`, `i-1` type of array indexing to fetch values for interpolation.

**Comment by data-panda** [comment]
Or to put it more simply 

what is the best way to determine the leaf cell which contains a point P given by it coordinate `(x,y,z)`. 

The brute force way is to iterate over all the quadrant and see if the point lies in a quadrant but it would not be the aptest way to do it for hundreds of points in every iteration. Is there a more simple approach that could be taken?

**Comment by cburstedde** [comment]
Check out the p4est_search functions. They can search for any object, for example points, and several of them at the same time. You can use the function that only looks in the local partition or the function that finds the correct remote process for a point, or one that does both.

**Comment by data-panda** [comment]
@cburstedde closing this for now! Thanks for your reply.
