### ISSUE TITLE
problem creating lnodes for a special case

### ISSUE THREAD

**Issue by vryy** [cburstedde/p4est#65]
Hello

I would like to report an instance that p4est_lnodes does not work correctly. The mesh for the given problem can be seen in the figure below. There are one element inside another one. This is to simulate a use case when the inner element will be deactivated initially and then reactivated later during simulation.

![hollow_cube](https://user-images.githubusercontent.com/13781578/63963147-a8f35280-ca94-11e9-9871-7d7962c19ea3.png)

There are 12 nodes in the mesh. However when p4est_lnodes is called, there are only 11 nodes are given numbering. In addition, there is one node with number -1. The output is:

[p4est] Into p8est_ghost_new CORNER
[p4est] Done p8est_ghost_new
[p4est] Into p8est_lnodes_new, degree 1
data.nodes_per_volume: 0
data.nodes_per_face: 0
data.nodes_per_edge: 0
data.nodes_per_corner: 1
lnodes->element_nodes: 6 10 0 1 10 9 2 3 4 5 -1 6 7 8 9 10
[p4est] Done p8est_lnodes_new with 11 global nodes

 The code and input file to reproduce this problem is in the attachment 

[ex_lnodes.zip](https://github.com/cburstedde/p4est/files/3556749/ex_lnodes.zip)

**Comment by cburstedde** [comment]
Running with the latest develop version of p4est in 3D, the program never gets past
conn = p4est_connectivity_read_inp(filename);

Could you double check your .inp file?

**Comment by vryy** [comment]
For me it can get past. Nevertheless a seg fault error is produced.

The output is:

hbui@bermuda:/media/WORK/workspace/p4est/cmake_build$ ./ex_lnodes_3d ../hollow_cube.inp 
[libsc] This is libsc 2.2
[p4est] This is p4est 2.2.1-85ab
[p4est] CPP                      mpicc -E
[p4est] CPPFLAGS                  -I/opt/petsc-3.11.0/include
[p4est] CC                       mpicc
[p4est] CFLAGS                   -g -O2
[p4est] LDFLAGS                   -L/opt/petsc-3.11.0/lib
[p4est] LIBS                     -lmetis -llapack -lcblas -lf77blas -latlas -lz -lm   
Take a close look on 2D inp or 3D inp. P4est program can only read 2D inp and P8est program can only read 3D inp. So mixing up won't work
[p4est] Reading connectivity from ../hollow_cube.inp
[p4est] New connectivity with 2 trees and 12 vertices

**Comment by cburstedde** [comment]
With the latest develop version, I have tried to read the .inp file using p4est_step2 and p8est_step2. Neither works (in 3D, the file does not pass some internal checks). How does this work for you?
