### ISSUE TITLE
Can data live in face, edge or corner in p4est?

### ISSUE THREAD

**Issue by GumpXiaoli** [cburstedde/p4est#66]
In my understanding, data in one octant means this data lives in the cell center. Can data live in other places (face, edge or corner) like AMReX?

**Comment by cburstedde** [comment]
> In my understanding, data in one octant means this data lives in the cell center. Can data live in other places (face, edge or corner) like AMReX?

We do not allocate memory for such data inside of p4est.  You are free to
allocate such data yourself.  What you'll need is a lookup structure that
associates your DOF with the elements.  It must be consistent in parallel.

For low- and high-order continuous finite elements, we supply such a structure
as p4est_lnodes.  It is used in example/steps/ number 4.

If p4est_lnodes does not supply the right format for your application, you can
either modify it by changing our code, or rewrite your own tables from scratch
based on p4est_iterate (the latter will give you more control on what you're
doing; you may look at the source of p4est_mesh for one such design).

**Comment by cburstedde** [comment]
Another trick due to Toby is to use p4est_lnodes with a degree of 2. You will get exactly one node number for each face and edge interface, each corner and each cell. You may then take a count and associate any data of your choice with these nodes.
