### ISSUE TITLE
Saving/loading global data with p4est_save/load

### ISSUE THREAD

**Issue by arthurbawin** [cburstedde/p4est#68]
Hello !

I would like to save some additional global data when saving the forest into a file with p4est_save. This data is related to the forest itself, and is typically what I put in the user_pointer, so I don't want to replicate it for each octant by adding it to my user_data structure. Is there a way to give the p4est this single data, save it and load it back later ? I'm sure it is straightforward, but I don't really know where to search...

Thank you for your time and for all your work !
Arthur

**Comment by cburstedde** [comment]
Arthur,

> I would like to save some additional global data when saving the forest into a file with p4est_save. This data is related to the forest itself, and is typically what I put in the user_pointer, so I don't want to replicate it for each octant by adding it to my user_data structure. Is there a way to give the p4est this single data, save it and load it back later ? I'm sure it is straightforward, but I don't really know where to search...

no, you may just write this data to a separate file on rank 0.

Carsten
