### ISSUE TITLE
libsc.so does not compile

### ISSUE THREAD

**Issue by markyoder** [cburstedde/p4est#71]
Can't seem to get `libsc.so` to compile -- either from the p4est .configure;make;make install or from the libsc repository. Looking through the `./src/.libs`, `libsc.so` is there, but it is a link to nothing; the source file, `libsc-2.2.so` does not exist. 

the tail end of the output looks like this:
```
libtool: link: icc -fpic -std=c++11 -o libb64/.libs/sc_b64dec libb64/sc_b64dec-b64dec.o  ./src/.libs/libsc.so -llapack -lblas -lz
make[1]: *** [example/bspline/sc_bspline_per] Error 1
make[1]: *** [example/logging/sc_logging] Error 1
make[1]: *** [example/bspline/sc_bspline] Error 1
make[1]: *** [example/dmatrix/sc_dmatrix] Error 1
make[1]: *** [example/options/sc_options] Error 1
icc: error #10236: File not found:  './src/.libs/libsc.so'
icc: error #10236: File not found:  './src/.libs/libsc.so'
make[1]: *** [libb64/sc_b64enc] Error 1
make[1]: *** [libb64/sc_b64dec] Error 1
make[1]: Leaving directory `/scratch/myoder96/Downloads/p4est/p4est-2.2/sc'
make: *** [all-recursive] Error 1
Making install in sc
make[1]: Entering directory `/scratch/myoder96/Downloads/p4est/p4est-2.2/sc'
/bin/sh ./libtool  --tag=CC   --mode=link icc  -fpic -std=c++11    -o libb64/sc_b64enc libb64/sc_b64enc-b64enc.o ./src/libsc.la -llapack -lblas -lz   
libtool: link: icc -fpic -std=c++11 -o libb64/.libs/sc_b64enc libb64/sc_b64enc-b64enc.o  ./src/.libs/libsc.so -llapack -lblas -lz
icc: error #10236: File not found:  './src/.libs/libsc.so'
make[1]: *** [libb64/sc_b64enc] Error 1
make[1]: Leaving directory `/scratch/myoder96/Downloads/p4est/p4est-2.2/sc'
make: *** [install-recursive] Error 1
```

**Comment by markyoder** [comment]
Also, not sure if it's related, but we get this `lua` error as well:

```
configure: - P4EST -------------------------------------------------
We did not find a recent lua containing the function lua_createtable.
This is OK if the following does not matter to you:
Including sc_lua.h in your code will abort the compilation.
You can fix this by compiling a working lua and pointing LIBS to it.
```

But the version oe `lua` we are running (I think 5.3.1) does have `lua_createtable()`; tried loading the latest `lua, 5.3.5, and we still get the error.

**Comment by cburstedde** [comment]
The configure logic not picking up the lua function is strange. Otherwise, not having lua is no issue for compiling p4est. The lua check is removed in the prev3-develop branch.

**Comment by cburstedde** [comment]
Some paths for the linker may be missing, which could explain both issues. Can you experiment with LIBS= and/or LDFLAGS= ?

For extra portability you may configure --without-blas.

**Comment by cburstedde** [comment]
To work with less external dependencies, you may consider the branch prev3-develop.

**Comment by markyoder** [comment]
Thanks Carsten. I eventually figured this out, and I wish I could remember
what it was -- except that it was something simple. If this thread can be
of help to somebody in the future, perhaps it is, 'think simple,' like
compiler version via `module load` I may have been using the wrong linker.


Mark Yoder, PhD
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"If you bore me, you lose your soul (to me)..."
~belly
