### ISSUE TITLE
missing configure script?

### ISSUE THREAD

**Issue by nw236** [cburstedde/p4est#72]
I just cloned the git repository and tried to compile p4est, there is however no configure scrip in the root directory. It is present in the tar-ball available from the p4est website, and that version compiles without problems.

Am I missing something?

**Comment by rubendibattista** [comment]
In order to build the git version you need to use the `./bootstrap` script.

Beware that the git repo ships `sc` lib as a submodule... Be sure you checked it out correctly.

**Comment by nw236** [comment]
Many thanks for the quick response. Now it works.
