### ISSUE TITLE
compilation error on Mac

### ISSUE THREAD

**Issue by andrewwinters5000** [cburstedde/p4est#73]
There is a conflict of function `wait()` in the `particles2.c` example file between the Mac Command Line Tools and p4est. If I changed the name of the function within `particles2.c` then p4est built successfully.

**Comment by cburstedde** [comment]
> There is a conflict of function `wait()` in the `particles2.c` example file between the Mac Command Line Tools and p4est. If I changed the name of the function within `particles2.c` then p4est built successfully. 

Thanks, this should be fixed in the "develop" branches.  Have you tried them?

**Comment by andrewwinters5000** [comment]
Yup that fixes it, many thanks!
