### ISSUE TITLE
Determining neighbouring nodes from lnodes

### ISSUE THREAD

**Issue by esys-escript** [cburstedde/p4est#74]
If I had a mesh similar to Fig. 5. in the paper Carsten Burstedde, Lucas C. Wilcox, and Omar Ghattas, SIAM Journal on Scientific Computing _33_ no. 3 (2011), then, given a node in this mesh (say, node 7), how can I determine the global numbers of the neighbouring nodes from the lnodes structure? What is the easiest way to determine this information?

**Comment by cburstedde** [comment]
The most common way is to loop over the elements and for each element to loop over the relevant nodes. They are indexed in the p4est_lnodes_t structure. We do not have a direct lookup from a node back to its referring elements. You may add some bookkeeping code to track this yourself. However, for finite element type calculations such is rarely needed.
