### ISSUE TITLE
Merge of branch feature-mesh-edge into master

### ISSUE THREAD

**Issue by thomasgillis** [cburstedde/p4est#75]
Dear Prof. Burstedde,

I have been using the branch `feature-mesh-edge` for a while without any problem.
As I noticed that you are currently active on the repo, do you plan to merge it in the next major release?
If not already planned, could you consider it?

Thank you for your support

**Comment by cburstedde** [comment]
Yes, this code will be included. It should be safe to use. I need to find some time to review the conventions of the data structure, so in the worst case, there will be a minor redefinition.

Please let me know if anything does not work as documented with this functionality.

**Comment by thomasgillis** [comment]
Great, thanks!
I didn't encounter any mismatch between the doc and the behavior of the code

**Comment by cburstedde** [comment]
> Great, thanks!
> I didn't encounter any mismatch between the doc and the behavior of the code

That's good to know.  Thanks to Dr. Michael Lahnert for collaborating on the
data structure and putting together the implementation.

**Comment by cburstedde** [comment]
Hi I've merged feature-mesh-edge into develop. Unchanged fwiw. Please let me know if there's any trouble.
