### ISSUE TITLE
neighbouring quads

### ISSUE THREAD

**Issue by KyleYang0320** [cburstedde/p4est#76]
I'm doing some CFD research on P4est and I had difficulty locating the exact position of a certain point. When I get the coordinates of a certain point, how can I find which quad the point locates in and how can I find other quads which neighbour this quad.

**Comment by data-panda** [comment]
maybe issue #64 is somewhat related to this question and the response from Carsten could help.

**Comment by KyleYang0320** [comment]
> maybe issue #64 is somewhat related to this question and the response from Carsten could help.

Thx, I learned about the  p4est_search and now I can find the information of the certain quad. However, what I'm concerned about is the user_data in this quad struct. If the quad is in not in the local process or the ghost layer, how can I get the user_data information stored in this quad?  Besides, if I have a large amount of certatin point data to process, is there any feasible approach to solve this problem?

**Comment by data-panda** [comment]
@KyleYang0320 if you were able to find the "quad" given the location "x,y,z" then it would be helpful if you can share a small code snippet. I didn't tried the suggested solution since I moved on with other things but it would be helpful to me/others.

**Comment by cburstedde** [comment]
If the search gives you remote quadrants, you would need to write messages yourself to request their data.
Check out example/particles for a demonstration.

If you are looking for data from ghost quadrants, look at p4est_ghost_exchange and friends.
