### ISSUE TITLE
Hanging node for mixed discretization

### ISSUE THREAD

**Issue by vryy** [cburstedde/p4est#82]
Hello, I have a question regarding Q2P1 discretization (Q2 for displacement and P1 for pressure). I could get the hanging nodes for displacement but do not know how to obtain the hanging information for pressure because it is based on the linear mesh (A hanging node for pressure is not a hanging one w.r.t displacement (see figure below)). Can this case be handled by p4est?

![water_pressure](https://user-images.githubusercontent.com/13781578/90763345-d14c1080-e2e6-11ea-94fc-4863a0c6d869.png)

**Comment by cburstedde** [comment]
If you want a continuous piecewise linear discretization, use p4est_nodes or p4est_lnodes (1) and see the documentation comments in the header files.
