### ISSUE TITLE
error about p4est_ghost_exchange_data 

### ISSUE THREAD

**Issue by PheiGao** [cburstedde/p4est#84]
I convert hex addresses to line numbers with addr2line. the error point to p4est_ghost_exchange_data. my code is :

p4est_ghost_t* ghost = p4est_ghost_new (p4est, P4EST_CONNECT_FULL);
samr_data_t* ghost_data =
P4EST_ALLOC (samr_data_t, ghost->ghosts.elem_count);

p4est_ghost_exchange_data (p4est, ghost, ghost_data);

// gather face,egde,node neighbor
p4est_iterate(
p4est,
ghost,
(void*) ghost_data,
NULL,
smar_face_iter_gather_face_nei,
smar_edge_iter_gather_edge_nei,
smar_node_iter_gather_node_nei);

p4est_ghost_destroy (ghost);
P4EST_FREE (ghost_data);

is my code correct?

**Comment by cburstedde** [comment]
If you're calling p4est_ghost_exchange_data, make sure that the data_size of p4est and the contents of the user data is what you want. It must match sizeof (samr_data_t). Please see the documentation comment for this function in p4est_ghost.h. The array you allocate is filled with the ghost data received.

If instead you'd want  to send data that you allocate yourself, use p4est_ghost_exchange_custom.

If it still breaks, please provide a backtrace of the crash.

**Comment by cburstedde** [comment]
Hey, just checking. Any news?

**Comment by PheiGao** [comment]
Thanks for your reply. I input a wrong parameter to p4est-alloc. Finally the issue is settled



发自我的iPhone


------------------ Original ------------------
From: Carsten Burstedde ***@***.***&gt;
Date: Tue,Mar 9,2021 10:03 PM
To: cburstedde/p4est ***@***.***&gt;
Cc: GaoFei ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [cburstedde/p4est] error about p4est_ghost_exchange_data  (#84)





 
Hey, just checking. Any news?

**Comment by cburstedde** [comment]
Thanks for your reply!
