### ISSUE TITLE
Weighted Partition with Metis

### ISSUE THREAD

**Issue by ackirby88** [cburstedde/p4est#89]
Hi Cartsten,

I found a corner case issue for Weighted Partitioning combined with Metis connectivity reordering.
I have a 2D unstructured mesh with 3724 quadrants, partitioned across 3 MPI ranks.

In the top image, you can see that when I use a *weight function* for partitioning, which only assigns **weight = 1 for all quadrants**, p4est assigns the partition cut to the lower ranks.  

In contrast, if I set the *weight_fn* to NULL, then I get the correct partition in the bottom attached image.  

---

*Metis Partition with weight function (all weights=1): 3724 trees, 3 ranks*
![Metis_Weighted_Partition](https://user-images.githubusercontent.com/37650539/103569670-b644fc00-4e95-11eb-84a6-773f48d2abf2.png)

*Metis Partition with no weighing function: 3724 trees, 3 ranks*
![Metis_Nonweighted_Partition](https://user-images.githubusercontent.com/37650539/103567053-14231500-4e91-11eb-8b5a-3e1027fb845e.png)

---

The reason why this happens seems to stem back to your commit 78f1c64844afb24cd4fc335dff0ad1de8c358b6b from about 10 years ago.  
The issue appears to be that you assign the partition cut to the lower rank, which contrasts to METIS's and the nonweighted p4est partition assignment by a single element.  

I was wondering if you recall a specific reason why you chose why the low end must always receive the cut?  
Thanks,  
A. Kirby  

**METIS Partition Assignment**: (tree_id after connectivity reassignment)
|Rank | Start tree_id | End tree_id | # trees |
| ------ | ---------------- | ---------------- | ---------: |
| 0 |  0 | 1240 |  1241 |
| 1 |  1241 | 2481 |  1241 |
| 2 |  2482 | 3723 |  1242 |  

**p4est (no weighting function) Partition Assignment**:  
|Rank | Start tree_id | End tree_id | # trees |
| ------ | ---------------- | ---------------- | ---------: |
| 0 |  0 | 1240 |  1241 |  
| 1 |  1241 | 2481 |  1241 |  
| 2 |  2482 | 3723 |  1242 |  

**p4est (*weight_fn* -- weights = 1) Partition Assignment**:  
|Rank | Start tree_id | End tree_id | # trees |
| ------ | ----------------- | ---------------- | --------:|
| 0 |  0 | 1241 |  1242 |  
| 1 |  1242 | 2482 |  1241 |  
| 2 |  2483 | 3723 |  1241 |

**Comment by cburstedde** [comment]
Hi Andrew, thanks for your research. Indeed, it would be better if equal weights (1, or any other value for that matter) always resulted in the exact same partitioning that is obtained with a NULL weight callback function.

Let me ask our resident partition expert @tim-griesbach if he can come up with a (hopefully minimal) edit to resolve this issue.

**Comment by cburstedde** [comment]
We have checked this, and we see identical results with weight 1 and weight NULL. We see differences for equal weights greater than 1, which is expected by the formulas we're using. Would you be able to check/comment?

**Comment by ackirby88** [comment]
Hi Carsten, I can confirm the results you found with weight 1 and weight NULL are the same (the above results may have been on an old commit but I didn't keep track of the git commit that I used to get those results), and the difference when the weights > 1 but equal. Given that is the expected behavior from the formulas, then I'll close the issue since I can leverage that fact (weights=1) to get a proper partition.

**Comment by cburstedde** [comment]
> Hi Carsten, I can confirm the results you found with weight 1 and weight NULL are the same (the above results may have been on an old commit but I didn't keep track of the git commit that I used to get those results), and the difference when the weights > 1 but equal. Given that is the expected behavior from the formulas, then I'll close the issue since I can leverage that fact (weights=1) to get a proper partition.

Sounds great, thanks for the report, and thanks to @tim-griesbach for the investigation.
