### ISSUE TITLE
Expand p4est_connectivity_reorder

### ISSUE THREAD

**Issue by mugolotti** [cburstedde/p4est#93]
Hello,

I would like to make a recommendation for a possible p4est enhancement that would help be extremely helpful in speeding up our code. 
Hers is the description.

**Motivation**
I am working on a high-order CFD solver that uses p4est for feature-based AMR.
The solver is capable of handling high-order elements and follows the following set of operations for reading the connectivity of the elements from the grid file:

- PASS1: read the number of vertices and number of trees from the grid file. Then create p4est connectivity using `p4est_connectivity_new`.
- PASS2: read the nodes coordinates and element connectivities (very vertices of the element, i.e. "low-order" nodes") from the grid file. Then complete the connectivity using `p4est_connectivity_complete`.
- Reorder the connectivity using `p4est_connectivity_reorder`.
- Create p4est using `p4est_new_ext` and providing a callback function that, for each element, reopens the grid file (PASS3) and reads the remaining "high-order" nodes, and stores them in `p.user_data`.

**Description**
The PASS3 consists of finding a specific tree in the grid file and reading high-order node IDs. As of now, the only way to find that specific tree in the grid file is to skim the file and compare the first 4 node IDs (or 8 in 3D) of the tree to find with the first 4 node IDs (or 8 in 3D) of each element in the grid file. Evidently, this is a very time-consuming approach.

Alternatively, we could bookkeep the location of each element in the grid file (for instance line number for ASCII grid files or the bytes count for binary files) during PASS2 and save this data in an array ( `ElemLoc`). 
Then, during the PASS3, we can fast forward to the exact location of the tree in the grid file by using `ElemLoc[tree_id]`.
However, we lose track of the proper location of the trees in the array _ElemLoc_ after the trees are reordered by calling `p4est_connectivity_reorder`.

**Proposed solution**
Threfore, we propose to introduce a new function called `p4est_connectivity_reorder_ext` that carries out the same operations of the current `p4est_connectivity_reorder` function except that reurns the `newid` array.
Furthermore, the function `p4est_connectivity_reorder` will be recasted as follow:

`void`
`p4est_connectivity_reorder (sc_MPI_Comm comm, int k,p4est_connectivity_t * conn,p4est_connect_type_t ctype)`
`{`
 &nbsp;`     sc_array_t         *newid;`
 &nbsp;`     newid = p4est_connectivity_reorder_ext (comm, k, conn, ctype);`
 &nbsp;`     sc_array_destroy (newid);`
`}`

Other small code modifications are required in files: `p4est_extended.h`,`p8est_extended.h`, and `p4est_to_p8est.h`.

`newid` array will help us to map old indices to new indices and properly retrieve the element location into the `ElemLoc` array, thus speeding up the PASS3 for reading the high-order node IDs.

As a matter of fact, I already tested this change in my local branch (branched out from prev3-develop) and it works just fine!!

Thank you for your time and for your help,
Best regards,

Matteo

**Comment by cburstedde** [comment]
Thanks for the suggestion!

I'd just like to ask for a prototype that returns `void` as before and takes newid as an additional `sc_array` argument. This avoids memory leaks in case people forget to free the return value. On input, the array must exist and have byte size `sizeof (size_t)`, no matter the count. inside the function, call `sc_array_resize` on `newid` before using it. The input argument may be NULL, in which case it is allocated and freed inside the function. How does that sound?

**Comment by mugolotti** [comment]
You are actually right!
I forked from p4est repo, implemented your solution, and tested it.

Do you want me to open a pull request? on which branch should I do it?

Thanks again

**Comment by cburstedde** [comment]
Yes, please make a PR against the "develop" branch. Please make sure *not* to pull in anything from "prev3-develop," and to add doc/author_lastname.txt releasing your code under the FREEBSD license.

I'll look at it and might comment or push to the PR branch. Thanks!

**Comment by cburstedde** [comment]
Thanks, it's integrated! Please let me know if anything else comes up.

Currently we do not have a CI build with `METIS`, hence my not catching the naming issue. Would you want to add one as a fourth job in `.github/workflows/ci.yml`? No obligation at all, of course.

**Comment by cburstedde** [comment]
Resolved by #95.
