### ISSUE TITLE
p4est_ghost_expand expandable/failure

### ISSUE THREAD

**Issue by ligazetom** [cburstedde/p4est#98]
**Description**
I am in point of my project where I need to make region around my quadrant according to user-specified pixel radius. For that I need to make sure I have all of the quadrants in that radius accessible, so the worst case scenario is having the smaller quadrant (size of 1 pixel) at the partition edge.

I found out that if I call `p4est_ghost_expand` too many times I'll eventually get ASSERT failure for `p4est_ghost_is_valid`. It happens if there are at least 3 partitions and the 1st one tries to grab quadrants from the 3rd. 

Obviously that seems a little off to me, but nevermind, I am able to work around it, however there is no way of knowing how many times I can call expand before it fails. Is there some way I can know the number of possible expands before the whole ghost layer gets invalidated? I am working with images so memory is no issue here at the moment. 

**To Reproduce**
You can run step1 on at least 3 processes and adding ghost layer with for loop in main with `p4est_ghost_expand` call.

**Comment by ligazetom** [comment]
I propose to remove `P4EST_ASSERT (p4est_ghost_is_valid (p4est, ghost));` from `p4est_ghost_expand_internal` and call them inside functions that actually call 'p4est_ghost_expand_internal'. Then adding another function of type `bool` that would return `p4est_ghost_is_valid`. With this I could try expand as much as I need and if I hit a limit I'll do another pass with the magic number.

**Comment by ligazetom** [comment]
I needed this functionality very much and ASAP, so if there is better solution I will be glad to implement that. However I solved it by implementing my own 'p4est_ghost_is_valid' function, which is copy of the old one but every `return 0` is substituted by this:

static void HandleSynchronizedReturn(p4est_t *p4est, int *allFlags, int *okFlag, int mpisize, int mpirank)
{
  int i;
  MPI_Gather(okFlag, 1, MPI_INT, allFlags, 1, MPI_INT, 0, p4est->mpicomm);

  if (mpirank == 0)
  {
    for (i = 0; i < mpisize; ++i)
    {
      *okFlag = allFlags[i];
      if (*okFlag == 0) break;
    }
  }

  MPI_Bcast(okFlag, 1, MPI_INT, 0, p4est->mpicomm);

  if (!*okFlag)
  {
    if (mpirank == 0) P4EST_FREE(allFlags);
  }
}

`okFlag` is initialized to 1, and anytime previous `p4est_ghost_is_valid` would return 0, now instead I assign it to the `okFlag` and then gather all of the okFlag values from all other processes, check if at least one of them is zero (on the root), if it is zero I'll Bcast zero `okFlag` to everyone so they all have the same flag. `allFlags` is preallocated array of size `mpisize`. 

I really wish there was an easier way of how to tackle this, so I could avoid code copying, but it is what it is and it's doing exactly what I needed.

**Comment by cburstedde** [comment]
Thanks for the diagnostics. `p4est_ghost_expand` should be callable any number of times, eventually not adding any more quadrants to the ghost layer. The workaround makes `ghost_is_valid` collective, which is not how we'd like to use it.

I'd suggest changing the code such that expansion can safely be called any number of times. Maybe @tisaac knows more?

**Comment by tisaac** [comment]
I want to fix this, but I need a minimal example to figure out what's going on: can you either provide code or a p4p/p8p file for the mesh that's causing problems?

**Comment by ligazetom** [comment]
[p4est_step1.zip](https://github.com/cburstedde/p4est/files/6109600/p4est_step1.zip)

This is minimal code that is failing. Nothing special as I mentioned, just edited step1.c.

**Comment by tisaac** [comment]
@ligazetom #99 worked for me.  If you can, try that branch out before it's merged to see if it fixes the problem for you.

**Comment by ligazetom** [comment]
@tisaac I confirm #99 seems to be working properly. Did some more complex testing and I seem to be getting the same results so not even it does not assert ,but data are actually there as well. Good job, thanks.
